{{- if not .Values.clusterName }}
{{- fail "clusterName must not be empty" }}
{{- end }}
---
apiVersion: kubernetes.m.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: {{ .Values.clusterName }}
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: helm.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: {{ .Values.clusterName }}
spec:
  credentials:
    source: InjectedIdentity
{{- range $cluster, $values := .Values.remoteClusters }}
---
apiVersion: kubernetes.m.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: {{ $cluster }}
spec:
  credentials:
    source: Secret
    secretRef:
      name: {{ $values.secretRef.name }}
      namespace: {{ $values.secretRef.namespace }}
      key: {{ $values.secretRef.key }}
---
apiVersion: helm.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: {{ $cluster }}
spec:
  credentials:
    source: Secret
    secretRef:
      name: {{ $values.secretRef.name }}
      namespace: {{ $values.secretRef.namespace }}
      key: {{ $values.secretRef.key }}
{{- end }}
