apiVersion: module.elastisys.com/v1alpha1
kind: NodeLocalDNS
metadata:
  namespace: kube-system
  name: node-local-dns
spec:
  providerConfigs:
    helm: mc-node-local-dns
    kubernetes: mc-node-local-dns
  clusterDNS: {{ .Values.clusterDNS }}
  resources: {{ .Values.resources | toYaml | nindent 4 }}
  customConfig: {{ .Values.customConfig | toYaml | nindent 4 }}
  errorConfig: {{ .Values.errorConfig | toYaml | nindent 4 }}
  crossplane:
    compositionRef:
      name: node-local-dns
