---
templates:
  tekton-pipelines:
    condition: ck8sManagementCluster.enabled
    name: tekton-pipelines
    chart: charts/tekton-pipelines
    installed: {{ .Values | get "tektonPipelines.enabled" false }}
    version: 0.1.0
    namespace: tekton-pipelines
    labels:
      app: tekton
    needs:
      - kube-system/admin-namespaces
    values:
      - values/tekton.gotmpl
