{
 "title": "Backup status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_job_status_completion_time, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Time since last successful Harbor backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min((time()-kube_job_status_completion_time{job_name=~\"harbor-backup-cronjob-.*\", cluster=~\"$cluster\"})/3600)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Time since last successful InfluxDB backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min((time()-kube_job_status_completion_time{job_name=~\"influxdb-backup-[0-9]*\", cluster=~\"$cluster\"})/3600)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Time since last successful Velero backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule=\"velero-daily-backup\", cluster=~\"$cluster\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Time since last successful OpenSearch backup job",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min((time()-kube_job_status_completion_time{job_name=~\"opensearch-backup-.*\", cluster=~\"$cluster\"})/3600)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Time since last successful OpenSearch snapshot ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time()-elasticsearch_snapshot_stats_snapshot_start_time_timestamp{state=\"SUCCESS\", cluster=~\"$cluster\"})/3600"
    }
   ]
  },
  { "title": "Backup rclone sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "# Off-site backup replication is <<rclone-sync-state>>"
   }
  },
  {
   "title": "Status of backup rclone sync cronjobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (bucket) (label_replace(kube_cronjob_spec_suspend{cronjob=~\"rclone-sync-.*\"} == bool 0, \"bucket\", \"$1\", \"cronjob\", \"rclone-sync-(.*)\"))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Time since last successful backup rclone sync jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by (bucket) ((time()-label_replace(kube_job_status_completion_time{job_name=~\"rclone-sync-.*\"}, \"bucket\", \"$1\", \"job_name\", \"rclone-sync-(.*?)-(manual|[0-9-])*(manual|[0-9-])*\")))",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}