{
 "title": "Cluster api",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(capi_cluster_info, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Cluster phase",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capi_cluster_status_phase{name=~\"$cluster\", phase=\"Provisioned\"} == 1 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Provisioning\"} == 1) + 1 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Pending\"} == 1) + 1 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Unknown\"} == 1) + 1 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Deleting\"} == 1) + 1 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Failed\"} == 1) + 1",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cluster paused",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capi_cluster_spec_paused{name=~\"$cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cluster ready",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capi_cluster_status_condition{name=~\"$cluster\", type=\"Ready\", status=\"True\"} == 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"Ready\", status=\"Unknown\"} == 1) + 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"Ready\", status=\"False\"} == 1) + 2",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Control plane initialized",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneInitialized\", status=\"True\"} == 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneInitialized\", status=\"Unknown\"} == 1) + 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneInitialized\", status=\"False\"} == 1) + 2",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Control plane ready",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneReady\", status=\"True\"} == 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneReady\", status=\"Unknown\"} == 1) + 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneReady\", status=\"False\"} == 1) + 2",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Infrastructure ready",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capi_cluster_status_condition{name=~\"$cluster\", type=\"InfrastructureReady\", status=\"True\"} == 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"InfrastructureReady\", status=\"Unknown\"} == 1) + 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"InfrastructureReady\", status=\"False\"} == 1) + 2",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total control plane replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capi_kubeadmcontrolplane_status_replicas{name=~\"${cluster}-control-plane\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Unavailable control plane replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capi_kubeadmcontrolplane_status_replicas_unavailable{name=~\"${cluster}-control-plane\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Control plane replicas",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "capi_machine_status_condition{name=~\"${cluster}-control-plane.*\", type=\"Ready\"} == 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total MachineDeployment replicas",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "capi_machinedeployment_status_replicas{cluster_name=~\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Unavailable MachineDeployment replicas",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "capi_machinedeployment_status_replicas_unavailable{cluster_name=~\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MachineDeployment replicas",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "capi_machine_status_condition{cluster_name=~\"$cluster\", name!~\".*control-plane.*\", type=\"Ready\"} == 1",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}