{
 "title": "Daily-checks",
 "tags": [ "daily" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Elasticsearch snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Elasticsearch oldest snapshot age",
   "type": "stat",
   "description": "The age of the oldest snapshot currently available. This can help you determine if the retention policy is working. Is the age always increasing or does it regularly decrease when the oldest snapshot is removed?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - elasticsearch_snapshot_stats_oldest_snapshot_timestamp"
    }
   ]
  },
  {
   "title": "Elasticsearch number of snapshots",
   "type": "stat",
   "description": "Shows the number of snapshots stored. This is for keeping track of retention. If the count just keeps increasing, something is wrong with the SLM retention.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "elasticsearch_snapshot_stats_number_of_snapshots"
    }
   ]
  },
  { "title": "S3 buckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Time since last modified object",
   "type": "stat",
   "description": "This shows the time since an object was last modified for each bucket. If the backups are working objects should be added at least every 24 hours.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (bucket) (time() - max_over_time(s3_last_modified_object_date[1h]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 total usage",
   "type": "graph",
   "description": "Show the total size of the *selected* buckets. This is for keeping track of the usage and avoid hitting quota limits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(s3_objects_size_sum_bytes[1h]))"
    }
   ]
  },
  {
   "title": "Bucket sizes",
   "type": "graph",
   "description": "Shows the size of all buckets used by Compliant Kubernetes. Note that this does *not* show *all* buckets, only those configured for the environment.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (bucket) (max_over_time(s3_objects_size_sum_bytes[1h]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "InfluxDB database size",
   "type": "stat",
   "description": "The size of the individual databases (service_cluster and workload_cluster). Note that you should not rely on this to calculate the total size of the volume. This is just for checking the size of these specific databases.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "influxdb_service_cluster_size", "legendFormat": "Service cluster" },
    { "expr": "influxdb_workload_cluster_size", "legendFormat": "Workload cluster" }
   ]
  },
  {
   "title": "Additional checks",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "content": "In addition to these panels, you should also check the Persistent Volumes and Backups dashboards.\n\n\n\n\n"
  }
 ]
}