{
 "title": "Harbor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "harbor health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "harbor_health" }
   ]
  },
  {
   "title": "component up status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "harbor_up", "legendFormat": "{{component}}" }
   ]
  },
  {
   "title": "system info",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "harbor_system_info" }
   ]
  },
  {
   "title": "artifact pulled",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "harbor_artifact_pulled", "legendFormat": "Project: {{project_name}}" }
   ]
  },
  {
   "title": "Project total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "harbor_project_total", "legendFormat": "Public: {{public}}" }
   ]
  },
  {
   "title": "project members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "harbor_project_member_total", "legendFormat": "Project: {{project_name}}" }
   ]
  },
  {
   "title": "Quota Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte",
     "legendFormat": "Project: {{project_name}}"
    }
   ]
  },
  {
   "title": "Project repo total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "harbor_project_repo_total", "legendFormat": "Project: {{project_name}}" }
   ]
  },
  {
   "title": "Genertal metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "go info",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_info{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "Process CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_cpu_seconds_total{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "Process opened fd",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "Go heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go allocated  memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go next gc bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go gc time 0.25",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.25\",job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go gc time 0.5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.5\",job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go gc time 0.75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.75\",job=~\"harbor.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API request time 0.5",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.5\"}",
       "legendFormat": "Operation: {{operation}}, Method: {{method}}, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "request time 0.9",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.9\"}",
       "legendFormat": "Operation: {{operation}}, Method: {{method}}, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "request time 0.99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.99\"}",
       "legendFormat": "Operation: {{operation}}, Method: {{method}}, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "harbor core request total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(harbor_core_http_request_total[5m])",
       "legendFormat": "Operation: {{operation}}, Method: {{method}}, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "harbor core inflight request",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_inflight_requests",
       "legendFormat": "Pod: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JobService Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "job service info",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_jobservice_info" }
     ]
    },
    {
     "title": "task queue pending size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_queue_size", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "task latency",
     "type": "graph",
     "description": "time period from last process of task queue",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_queue_latency", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "task concurrency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_concurrency", "legendFormat": "Type: {{type}}, Pool: {{pool}}" }
     ]
    },
    {
     "title": "tasks per minute",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(harbor_jobservice_task_total[1m])",
       "legendFormat": "Type: {{type}}, Status: {{status}}"
      }
     ]
    },
    {
     "title": "number of running scheduled job",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_scheduled_total" }
     ]
    },
    {
     "title": "task process time 0.5",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "Type: {{type}}, Status: {{status}}"
      }
     ]
    },
    {
     "title": "task process time 0.9",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.9\"}",
       "legendFormat": "Type: {{type}}, Status: {{status}}"
      }
     ]
    },
    {
     "title": "task process time 0.99",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "Type: {{type}}, Status: {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registry Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Registry request inflight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "registry_http_in_flight_requests",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Registry request rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(registry_http_requests_total[5m])",
       "legendFormat": "Handler: {{handler}}, Method: {{method}}"
      }
     ]
    },
    {
     "title": "registry storage cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(registry_storage_cache_total[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "registry request time 0.5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(registry_http_request_duration_seconds_bucket[10m]))",
       "legendFormat": "Handler: {{handler}}, Method: {{method}}"
      }
     ]
    },
    {
     "title": "registry request time 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_request_duration_seconds_bucket[10m]))",
       "legendFormat": "Handler: {{handler}}, Method: {{method}}"
      }
     ]
    },
    {
     "title": "registry request time 0.99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(registry_http_request_duration_seconds_bucket[10m]))",
       "legendFormat": "Handler: {{handler}}, Method: {{method}}"
      }
     ]
    },
    {
     "title": "registry request size 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_request_size_bytes_bucket[10m]))",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "registry response size 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_response_size_bytes_bucket[10m]))",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "registry storage action time 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_storage_action_seconds_bucket[10m]))",
       "legendFormat": "Action: {{action}}, Driver: {{driver}}"
      }
     ]
    }
   ]
  }
 ]
}