{
 "title": "Hierarchical Namespace Controller",
 "description": "Status of the HNC",
 "tags": [ "hnc" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(hnc_namespace_conditions, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Conditions",
   "type": "stat",
   "description": "A ***condition*** is some kind of problem affecting a namespace or cluster.\n\nNamespace conditions are reported in the status of the `HierarchyConfiguration` object in each namespace.",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hnc_namespace_conditions{cluster=\"$cluster\"}) by(Condition, Reason)",
     "legendFormat": "{{Reason}}"
    }
   ]
  },
  {
   "title": "Reconcilers hierconfig activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(hnc_reconcilers_hierconfig_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(hnc_reconcilers_hierconfig_concurrent_peak)",
     "legendFormat": "Concurrent peak"
    },
    {
     "expr": "sum(hnc_reconcilers_hierconfig_hierconfig_writes_total)",
     "legendFormat": "Hierconfig writes total"
    },
    {
     "expr": "sum(hnc_reconcilers_hierconfig_namespace_writes_total)",
     "legendFormat": "Namespace writes total"
    }
   ]
  },
  {
   "title": "Reconcilers object activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum(hnc_reconcilers_object_total{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(hnc_reconcilers_object_concurrent_peak{cluster=\"$cluster\"})",
     "legendFormat": "Concurrent peak"
    },
    {
     "expr": "sum(hnc_reconcilers_object_writes_total{cluster=\"$cluster\"})",
     "legendFormat": "Writes total"
    },
    {
     "expr": "sum(hnc_reconcilers_object_overwrites_total{cluster=\"$cluster\"})",
     "legendFormat": "Overwrites total"
    }
   ]
  }
 ]
}