{
 "title": "Prometheus / Time series",
 "description": "Shows how many time series per metric or job we have in prometheus.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "jobs", "query": { "query": "label_values(job)" } },
   { "name": "metrics", "query": { "query": "label_values(__name__)" } }
  ]
 },
 "panels": [
  {
   "title": "Total time series",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count ({job=~\"$jobs\", __name__=~\"$metrics\", __name__!=\"\"})"
    }
   ]
  },
  {
   "title": "Times series per job",
   "type": "graph",
   "description": "Time series per job",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by(job) ({job=~\"$jobs\", __name__!=\"\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time series per metric",
   "type": "graph",
   "description": "Time series per metric",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(__name__) ({__name__=~\"$metrics\", __name__!=\"\"})"
    }
   ]
  }
 ]
}