{
 "title": "ClusterComplianceReport: CIS, NSA, PSS",
 "description": "This Dashboard is used to visualise ClusterComplianceReport of the trivy-operator",
 "tags": [
  "trivy-operator",
  "security",
  "security scanning",
  "vulnerabilities",
  "CIS",
  "NSA",
  "PSS",
  "trivy"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n# ClusterComplianceReport: CIS, NSA, PSS\n\n[Info](https://aquasecurity.github.io/trivy-operator/v0.13.0/docs/crds/clustercompliance-report/)"
   }
  },
  {
   "title": "CIS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CIS benchmark",
     "type": "stat",
     "description": "CIS benchmark status",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "trivy_cluster_compliance{description=\"CIS Kubernetes Benchmarks\",status=\"Pass\",title=\"CIS Kubernetes Benchmarks v1.23\"}",
       "legendFormat": "Pass"
      },
      {
       "expr": "trivy_cluster_compliance{description=\"CIS Kubernetes Benchmarks\",status=\"Fail\",title=\"CIS Kubernetes Benchmarks v1.23\"}",
       "legendFormat": "Fail"
      },
      {
       "expr": "sum(trivy_cluster_compliance{description=\"CIS Kubernetes Benchmarks\",title=\"CIS Kubernetes Benchmarks v1.23\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "NSA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "NSA",
     "type": "stat",
     "description": "NSA status",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_cluster_compliance{description=\"National Security Agency - Kubernetes Hardening Guidance\",status=\"Pass\",title=\"National Security Agency - Kubernetes Hardening Guidance v1.0\"})",
       "legendFormat": "Pass"
      },
      {
       "expr": "sum(trivy_cluster_compliance{description=\"National Security Agency - Kubernetes Hardening Guidance\",status=\"Fail\",title=\"National Security Agency - Kubernetes Hardening Guidance v1.0\"})",
       "legendFormat": "Fail"
      },
      {
       "expr": "sum(trivy_cluster_compliance{description=\"National Security Agency - Kubernetes Hardening Guidance\",title=\"National Security Agency - Kubernetes Hardening Guidance v1.0\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "PSS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "PSS: Restricted",
     "type": "stat",
     "description": "PSS: Restricted status",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_cluster_compliance{description=\"Kubernetes Pod Security Standards - Restricted\",status=\"Pass\",title=\"Kubernetes Pod Security Standards - Restricted\"})",
       "legendFormat": "Pass"
      },
      {
       "expr": "sum(trivy_cluster_compliance{description=\"Kubernetes Pod Security Standards - Restricted\",status=\"Fail\",title=\"Kubernetes Pod Security Standards - Restricted\"})",
       "legendFormat": "Fail"
      },
      {
       "expr": "sum(trivy_cluster_compliance{description=\"Kubernetes Pod Security Standards - Restricted\",title=\"Kubernetes Pod Security Standards - Restricted\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "PSS: Baseline",
     "type": "stat",
     "description": "PSS: Baseline status",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_cluster_compliance{description=\"Kubernetes Pod Security Standards - Baseline\",status=\"Pass\",title=\"Kubernetes Pod Security Standards - Baseline\"})",
       "legendFormat": "Pass"
      },
      {
       "expr": "sum(trivy_cluster_compliance{description=\"Kubernetes Pod Security Standards - Baseline\",status=\"Fail\",title=\"Kubernetes Pod Security Standards - Baseline\"})",
       "legendFormat": "Fail"
      },
      {
       "expr": "sum(trivy_cluster_compliance{description=\"Kubernetes Pod Security Standards - Baseline\",title=\"Kubernetes Pod Security Standards - Baseline\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  }
 ]
}