{
 "title": "Falco",
 "description": "Grafana dashboard for Falco output events",
 "tags": [ "Falco" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(falco_events, cluster)"
    }
   },
   {
    "name": "priority",
    "query": {
     "query": "label_values(falco_events{cluster=~\"$cluster\"}, priority)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(falco_events{cluster=~\"$cluster\", priority=~\"$priority\"}, k8s_ns_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\"}, k8s_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Falco logs",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Detailed falco logs can be found in OpenSearch Dashboards:\n\n\n<<opensearchdashboardsURL>>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Violations per Cluster",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Violations per Priority",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (priority)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Violations per Rule",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (rule)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Violations per Namespace",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (k8s_ns_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Violations per Set",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}, \"k8s_set_name\", \"$1\", \"k8s_pod_name\", \"(.+)-.+\" )) by (k8s_ns_name, k8s_set_name)",
     "legendFormat": "{{k8s_ns_name}}/{{k8s_set_name}}"
    }
   ]
  },
  {
   "title": "Violations per Pod",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (k8s_ns_name, k8s_pod_name)",
     "legendFormat": "{{k8s_ns_name}}/{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Event Rate (average/5m)",
   "type": "timeseries",
   "description": "This shows all Falco events that take place according to type and time.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}[5m])) by (rule, k8s_pod_name, k8s_ns_name, cluster)",
     "legendFormat": "{{rule}} - {{k8s_ns_name}}/{{k8s_pod_name}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Event Rate by Priority (average/5m)",
   "type": "timeseries",
   "description": "This shows the rate at which Falco events takes place.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}[5m])) by (priority, cluster) ",
     "legendFormat": "Priority: {{priority}} -  {{cluster}}"
    }
   ]
  },
  {
   "title": "Event List",
   "type": "table",
   "description": "This shows all Falco events with details in sequential order.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(falco_events{cluster=~\"$cluster\", priority=~\"$priority\", k8s_ns_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (cluster, rule, priority, k8s_ns_name, k8s_pod_name, tags)"
    }
   ]
  }
 ]
}