{
 "title": "Harbor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Harbor health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "harbor_health" }
   ]
  },
  {
   "title": "System info",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(harbor_system_info) by (auth_mode, harbor_version)"
    }
   ]
  },
  {
   "title": "Total number of Projects (Public vs Private)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "harbor_project_total", "legendFormat": "{{public}}" }
   ]
  },
  {
   "title": "Total number of artifacts",
   "type": "stat",
   "description": "Total number of artifacts type in a project",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_artifact_total)",
     "legendFormat": "Project: {{project_name}}"
    }
   ]
  },
  {
   "title": "Quota usage",
   "type": "stat",
   "description": "Total used resources of a project",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_quota_usage_byte)",
     "legendFormat": "Project: {{project_name}}"
    }
   ]
  },
  {
   "title": "Component up status",
   "type": "timeseries",
   "description": "Running status of Harbor components",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_up", "legendFormat": "{{component}}" }
   ]
  },
  {
   "title": "Total repositories in a project",
   "type": "timeseries",
   "description": "Total number of repositories in a project",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_project_repo_total", "legendFormat": "Project: {{project_name}}" }
   ]
  },
  {
   "title": "Total members in a project",
   "type": "timeseries",
   "description": "Total number of members in a project",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_project_member_total", "legendFormat": "Project: {{project_name}}" }
   ]
  },
  {
   "title": "Quota Usage per project",
   "type": "timeseries",
   "description": "Total used resources of a project",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte",
     "legendFormat": "Project: {{project_name}}"
    },
    {
     "expr": "sum(harbor_project_quota_usage_byte)",
     "legendFormat": "Total:"
    }
   ]
  },
  {
   "title": "Number of Artifacts per project",
   "type": "timeseries",
   "description": "Total number of artifacts type in a project",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "harbor_project_artifact_total", "legendFormat": "Project: {{project_name}}" },
    {
     "expr": "sum(harbor_project_artifact_total)",
     "legendFormat": "Total:"
    }
   ]
  },
  {
   "title": "Images pulled per project",
   "type": "timeseries",
   "description": "Number of images pulled in a project",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_artifact_pulled", "legendFormat": "Project: {{project_name}}" }
   ]
  },
  {
   "title": "General metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "go info",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_info{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "Process CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_cpu_seconds_total{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "Process opened fd",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "Go heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go allocated  memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go next gc bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go gc time 0.25",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.25\",job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go gc time 0.5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.5\",job=~\"harbor.*\"}"
      }
     ]
    },
    {
     "title": "go gc time 0.75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.75\",job=~\"harbor.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API request time 0.5",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.5\"}",
       "legendFormat": "Operation: {{operation}}, Method: {{method}}, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "request time 0.9",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.9\"}",
       "legendFormat": "Operation: {{operation}}, Method: {{method}}, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "request time 0.99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.99\"}",
       "legendFormat": "Operation: {{operation}}, Method: {{method}}, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "harbor core request total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(harbor_core_http_request_total[5m])",
       "legendFormat": "Operation: {{operation}}, Method: {{method}}, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "harbor core inflight request",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_inflight_requests",
       "legendFormat": "Pod: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JobService Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "job service info",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_jobservice_info" }
     ]
    },
    {
     "title": "task queue pending size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_queue_size", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "task latency",
     "type": "graph",
     "description": "time period from last process of task queue",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_queue_latency", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "task concurrency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_concurrency", "legendFormat": "Type: {{type}}, Pool: {{pool}}" }
     ]
    },
    {
     "title": "tasks per minute",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(harbor_jobservice_task_total[1m])",
       "legendFormat": "Type: {{type}}, Status: {{status}}"
      }
     ]
    },
    {
     "title": "number of running scheduled job",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_scheduled_total" }
     ]
    },
    {
     "title": "task process time 0.5",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "Type: {{type}}, Status: {{status}}"
      }
     ]
    },
    {
     "title": "task process time 0.9",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.9\"}",
       "legendFormat": "Type: {{type}}, Status: {{status}}"
      }
     ]
    },
    {
     "title": "task process time 0.99",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "Type: {{type}}, Status: {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registry Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Registry request inflight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "registry_http_in_flight_requests",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Registry request rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(registry_http_requests_total[5m])",
       "legendFormat": "Handler: {{handler}}, Method: {{method}}"
      }
     ]
    },
    {
     "title": "registry storage cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(registry_storage_cache_total[5m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "registry request time 0.5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(registry_http_request_duration_seconds_bucket[10m]))",
       "legendFormat": "Handler: {{handler}}, Method: {{method}}"
      }
     ]
    },
    {
     "title": "registry request time 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_request_duration_seconds_bucket[10m]))",
       "legendFormat": "Handler: {{handler}}, Method: {{method}}"
      }
     ]
    },
    {
     "title": "registry request time 0.99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(registry_http_request_duration_seconds_bucket[10m]))",
       "legendFormat": "Handler: {{handler}}, Method: {{method}}"
      }
     ]
    },
    {
     "title": "registry request size 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_request_size_bytes_bucket[10m]))",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "registry response size 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_response_size_bytes_bucket[10m]))",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "registry storage action time 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_storage_action_seconds_bucket[10m]))",
       "legendFormat": "Action: {{action}}, Driver: {{driver}}"
      }
     ]
    }
   ]
  }
 ]
}