{
 "title": "Node Exporter Disk",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster:",
    "query": "label_values(node_uname_info{job=\"$job\"}, cluster)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "device",
    "label": "Drive:",
    "query": "label_values(node_disk_info{job=\"$job\",cluster=~\"$cluster\",instance=~\"$node\"}, device)"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint:",
    "query": "label_values(node_filesystem_avail_bytes{job=\"$job\",cluster=~\"$cluster\",device=~\"/dev/${device}.*\",mountpoint!~\"/(run|boot)(|/.*)\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total free space",
   "type": "stat",
   "description": "Unused Root FS",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=~\"$node\", job=\"$job\", mountpoint=~\"$mountpoint\"})"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "bargauge",
   "description": "Disk space used of root filesystems across selected hosts",
   "gridPos": { "h": 9, "w": 11, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(node_filesystem_avail_bytes{instance=~\"$node\", job=\"$job\", device=~\".*$device.*\", mountpoint=~\"$mountpoint\"} / node_filesystem_size_bytes{instance=~\"$node\", job=\"$job\", device=~\".*$device.*\", mountpoint=~\"$mountpoint\"})",
     "legendFormat": "{{instance}} ({{device}})"
    }
   ]
  },
  {
   "title": "Worst Average Disk Wait Time",
   "type": "stat",
   "description": "The worst average time across the selected hosts for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.\n",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  rate(node_disk_read_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])\n  /\n  rate(node_disk_reads_completed_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])\n)\n",
     "legendFormat": "Read wait time"
    },
    {
     "expr": "max(\n  rate(node_disk_write_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])\n  /\n  rate(node_disk_writes_completed_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])\n)\n",
     "legendFormat": "Write wait time"
    }
   ]
  },
  {
   "title": "Max Queue Size",
   "type": "stat",
   "description": "The highest average queue length of the requests that were issued to the device across the selected instances",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\", job=\"$job\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Minimum free space",
   "type": "stat",
   "description": "Smallest amount of free space across the selected hosts.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{instance=~\"$node\", job=\"$job\", mountpoint=~\"$mountpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps Completed",
     "type": "graph",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "description": "The number of bytes read from or written to the device per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "Bps", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "Disk Average Wait Time",
     "type": "graph",
     "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s", "label": "time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Read wait time avg"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Write wait time avg"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "graph",
     "description": "The average queue length of the requests that were issued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "none", "label": "aqu-sz" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "graph",
     "description": "The number of read and write requests merged per second that were queued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_merged_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Read merged"
      },
      {
       "expr": "rate(node_disk_writes_merged_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Write merged"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percentunit", "label": "%util" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - IO"
      },
      {
       "expr": "rate(node_disk_discard_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - discard"
      }
     ]
    },
    {
     "title": "Instantaneous Queue Size",
     "type": "graph",
     "description": "The number of outstanding requests at the instant the sample was taken. Incremented as requests are given to appropriate struct request_queue and decremented as they finish.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none", "label": "Outstanding req." }
     ],
     "targets": [
      {
       "expr": "node_disk_io_now{instance=~\"$node\",job=\"$job\",device=~\"$device\"}",
       "legendFormat": "{{instance}} {{device}} - IO now"
      }
     ]
    },
    {
     "title": "Disk IOps Discards completed / merged",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "iops", "label": "IOs" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_discards_completed_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Discards completed"
      },
      {
       "expr": "rate(node_disk_discards_merged_total{instance=~\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}} - Discards merged"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"$node\",job=\"$job\",device!~'rootfs',mountpoint=~\"$mountpoint\"}",
       "legendFormat": "{{instance}} {{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "file nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=~\"$node\",job=\"$job\",device!~'rootfs',mountpoint=~\"$mountpoint\"}",
       "legendFormat": "{{instance}} {{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"$node\",job=\"$job\"}",
       "legendFormat": "{{instance}} - Max open files\n"
      },
      {
       "expr": "node_filefd_allocated{instance=~\"$node\",job=\"$job\"}",
       "legendFormat": "{{instance}} - Open files\n"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "file Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{instance=~\"$node\",job=\"$job\",device!~'rootfs',mountpoint=~\"$mountpoint\"}",
       "legendFormat": "{{instance}} {{mountpoint}} - File nodes total"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly / Error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=~\"$node\",job=\"$job\",device!~'rootfs',mountpoint=~\"$mountpoint\"}",
       "legendFormat": "{{instance}} {{mountpoint}} - ReadOnly"
      },
      {
       "expr": "node_filesystem_device_error{instance=~\"$node\",job=\"$job\",device!~'rootfs',fstype!~'tmpfs',mountpoint=~\"$mountpoint\"}",
       "legendFormat": "{{instance}} {{mountpoint}} - Device error"
      }
     ]
    }
   ]
  }
 ]
}