{
 "title": "Pod Skew",
 "description": "Visualize how spread-out pods are across zones or nodes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "granularity",
    "label": "Granularity",
    "query": "label_topology_kubernetes_io_zone,node"
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_labels{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespaces",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\",node=~\"$node\",created_by_kind=~\"(ReplicaSet|StatefulSet)\"}, namespace)"
    }
   },
   {
    "name": "replicaset",
    "label": "ReplicaSets",
    "query": {
     "query": "label_values(kube_replicaset_owner{cluster=\"$cluster\",namespace=~\"$namespace\"}, owner_name)"
    }
   },
   {
    "name": "statefulset",
    "label": "StatefulSets",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\",node=~\"$node\",namespace=~\"$namespace\",created_by_kind=\"StatefulSet\"}, created_by_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "How To",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard shows how well Pods are spread out across Nodes or Zones.\n\n1. Select a cluster.\n2. Select granularity, by node or by zone\n3. Select the worker nodes that should be serving workloads.\n4. Select the Namespace to inspect.\n5. Apply further filtering on ReplicaSet or StatefulSet to\n   drill down to those of interest.\n\n<!--\nvim: filetype=markdown\n-->\n"
   }
  },
  {
   "title": "Terms",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "options": {
    "content": "# Skew\n\nDifference between Nodes or Zones with most and least amount of Pods.\n\nFor example, if one Node has 3 Pods and another Node has 1 then the skew\nis 2. A skew of 0 or 1 is normal, as means the Pods are evenly\ndistributed across the selected Nodes.\n\n<!--\nvim: filetype=markdown\n-->"
   }
  },
  {
   "title": "Overall Pods Each",
   "type": "piechart",
   "description": "Number of pods running on each Node or in each Zone",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by ($granularity) (\n\tkube_pod_info{cluster=~\"$cluster\", node=~\"$node\", created_by_kind=~\"ReplicaSet|StatefulSet\", namespace=\"$namespace\", created_by_name=~\"($replicaset-.*|$statefulset)\"}\n\t* on (node)\n\tgroup_left(label_topology_kubernetes_io_zone)\n\tkube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n)\n",
     "legendFormat": "{{$granularity}}"
    }
   ]
  },
  { "title": "ReplicaSet $replicaset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "replicaset" },
  {
   "title": "Skew",
   "type": "gauge",
   "description": "Difference in number of pods across zones. E.g. if one zone has 3 pods and another pod has 1 then the skew is 2. A skew of 0 or 1 is normal.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "# largest amount of pods in the zone/node\nmax by (owner_name) (\n  sum by ($granularity, owner_name) (\n    # matching pods\n    kube_pod_info{cluster=~\"$cluster\", node=~\"$node\", created_by_kind=\"ReplicaSet\", namespace=\"$namespace\"}\n    # with the name of the deployment merged in\n    * on (created_by_name)\n    group_left (owner_name)\n    label_replace(kube_replicaset_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$replicaset\"}, \"created_by_name\", \"$1\", \"replicaset\", \"(.*)\")\n    # and zones merged in, if available\n    * on (node)\n    group_left(label_topology_kubernetes_io_zone)\n    kube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n  )\n)\n-\n# smallest amount of pods in the zone/node\nmin by (owner_name) (\n  sum by ($granularity, owner_name) (\n    kube_pod_info{cluster=~\"$cluster\", node=~\"$node\", created_by_kind=~\"ReplicaSet\", namespace=\"$namespace\"}\n    * on (created_by_name)\n    group_left (owner_name)\n    label_replace(kube_replicaset_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$replicaset\"}, \"created_by_name\", \"$1\", \"replicaset\", \"(.*)\")\n    * on (node)\n    group_left(label_topology_kubernetes_io_zone)\n    kube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n    or on (node)\n    label_replace(\n      kube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}*0\n    , \"owner_name\", \"$replicaset\", \"\", \"\")\n  )\n)",
     "legendFormat": "{{created_by_name}}"
    }
   ]
  },
  {
   "title": "Pods Each",
   "type": "piechart",
   "description": "Share of pods between each node or zone",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by ($granularity) (\n\tkube_pod_info{cluster=~\"$cluster\", node=~\"$node\", created_by_kind=\"ReplicaSet\", namespace=\"$namespace\"}\n  * on (created_by_name)\n  group_left (owner_name)\n  label_replace(kube_replicaset_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$replicaset\"}, \"created_by_name\", \"$1\", \"replicaset\", \"(.*)\")\n\t* on (node)\n\tgroup_left(label_topology_kubernetes_io_zone)\n\tkube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n)\n",
     "legendFormat": "{{$granularity}}"
    }
   ]
  },
  {
   "title": "Pods each over time",
   "type": "timeseries",
   "description": "Number of pods deployed on each Zone",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count by ($granularity, namespace, created_by_kind, owner_name) (\n  kube_pod_info{cluster=~\"$cluster\", node=~\"$node\", namespace=\"$namespace\", created_by_kind=\"ReplicaSet\"}\n  * on (created_by_name)\n  group_left(owner_name)\n  label_replace(kube_replicaset_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$replicaset\"}, \"created_by_name\", \"$1\", \"replicaset\", \"(.*)\")\n  * on (node)\n  group_left(label_topology_kubernetes_io_zone)\n  kube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n)",
     "legendFormat": "{{created_by_kind}} {{owner_name}} in {{$granularity}}"
    }
   ]
  },
  { "title": "StatefulSet $statefulset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 459 }, "repeat": "statefulset" },
  {
   "title": "Skew",
   "type": "gauge",
   "description": "Difference in number of pods across zones. E.g. if one zone has 3 pods and another pod has 1 then the skew is 2. A skew of 0 or 1 is normal.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 460 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (created_by_name) (\n  sum by ($granularity, created_by_name) (\n    kube_pod_info{cluster=~\"$cluster\", node=~\"$node\", created_by_kind=\"StatefulSet\", created_by_name=~\"$statefulset\", namespace=\"$namespace\"}\n    # join to get zone label\n    * on (node)\n    group_left(label_topology_kubernetes_io_zone)\n    kube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n  )\n)\n-\n# same as above but with an extra join to include empty zones/nodes\nmin by (created_by_name) (\n  sum by ($granularity, created_by_name) (\n    kube_pod_info{cluster=~\"$cluster\", node=~\"$node\", created_by_kind=\"StatefulSet\", created_by_name=~\"$statefulset\", namespace=\"$namespace\"}\n    * on (node)\n    group_left(label_topology_kubernetes_io_zone)\n    kube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n    or on ($granularity)\n    label_replace(\n      kube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}*0\n    ,\"created_by_name\", \"$statefulset\", \"\", \"\")\n  )\n)\n",
     "legendFormat": "{{created_by_name}}"
    }
   ]
  },
  {
   "title": "Pods Each",
   "type": "piechart",
   "description": "Share of pods between each node or zone",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 460 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by ($granularity) (\n\tkube_pod_info{cluster=~\"$cluster\", node=~\"$node\", created_by_kind=~\"StatefulSet\", namespace=\"$namespace\", created_by_name=~\"$statefulset\"}\n\t* on (node)\n\tgroup_left(label_topology_kubernetes_io_zone)\n\tkube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n)\n",
     "legendFormat": "{{$granularity}}"
    }
   ]
  },
  {
   "title": "Pods each over time",
   "type": "timeseries",
   "description": "Number of pods deployed on each Zone",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 460 },
   "targets": [
    {
     "expr": "count by ($granularity, namespace, created_by_kind, created_by_name) (\nkube_pod_info{cluster=~\"$cluster\", node=~\"$node\", namespace=\"$namespace\", created_by_kind=~\"StatefulSet\", created_by_name=~\"$statefulset\"}\n* on (node)\ngroup_left(label_topology_kubernetes_io_zone)\nkube_node_labels{cluster=~\"$cluster\", node=~\"$node\"}\n)",
     "legendFormat": "{{created_by_kind}} {{created_by_name}} in {{$granularity}}"
    }
   ]
  }
 ]
}