{
 "title": "Uptime and status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Customer API server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (target) (probe_success{target=\"user-api-server\"})"
    }
   ]
  },
  {
   "title": "Dex",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (target) (probe_success{target=\"dex\"})"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (target) (probe_success{target=\"grafana\"})"
    }
   ]
  },
  {
   "title": "Harbor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (target) (probe_success{target=\"harbor\"})"
    }
   ]
  },
  {
   "title": "OpenSearch Dashboards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (target) (probe_success{target=\"opensearch-dashboards\"})"
    }
   ]
  },
  {
   "title": "OpenSearch status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_cluster_health_status{color=\"green\"} or elasticsearch_cluster_health_status{color=\"yellow\"} * 0.5)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (target) (probe_success)",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "sum(elasticsearch_cluster_health_status{color=\"green\"} or (elasticsearch_cluster_health_status{color=\"yellow\"} * 0.5) or (elasticsearch_cluster_health_status{color=\"red\"} * 0))",
     "legendFormat": "opensearch"
    }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (target) (probe_success)",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "sum(elasticsearch_cluster_health_status{color=\"green\"} or (elasticsearch_cluster_health_status{color=\"yellow\"}) or (elasticsearch_cluster_health_status{color=\"red\"} * 0))",
     "legendFormat": "opensearch"
    }
   ]
  }
 ]
}