{
 "title": "Backup status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_job_status_completion_time, cluster)"
    }
   },
   {
    "name": "schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total, schedule)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Time since last successful backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Time since last successful Harbor backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min((time()-kube_job_status_completion_time{job_name=~\"harbor-backup-cronjob-.*\", cluster=~\"$cluster\"})/3600)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Time since last successful Velero backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule=\"velero-daily-backup\", cluster=~\"$cluster\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Time since last successful OpenSearch backup job",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min((time()-elasticsearch_snapshot_stats_latest_snapshot_timestamp_seconds{cluster=~\"$cluster\"})/3600)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Time since last successful OpenSearch snapshot ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time()-elasticsearch_snapshot_stats_snapshot_start_time_timestamp{state=\"SUCCESS\", cluster=~\"$cluster\"})/3600"
    }
   ]
  },
  { "title": "Backup per hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Velero backup per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup success -  {{cluster}}"
    },
    {
     "expr": "sum(increase(velero_backup_failure_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup failure -  {{cluster}}"
    },
    {
     "expr": "sum(increase(velero_backup_partial_failure_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup partial failure -  {{cluster}}"
    },
    {
     "expr": "sum(increase(velero_backup_deletion_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup deletion success -  {{cluster}}"
    },
    {
     "expr": "sum(increase(velero_backup_deletion_failure_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup deletion failure -  {{cluster}}"
    }
   ]
  },
  { "title": "Backup rclone sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "# Off-site backup replication is <<rclone-sync-state>>"
   }
  },
  {
   "title": "Status of backup rclone sync cronjobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (bucket) (label_replace(kube_cronjob_spec_suspend{cronjob=~\"rclone-sync-.*\"} == bool 0, \"bucket\", \"$1\", \"cronjob\", \"rclone-sync-(.*)\"))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Time since last successful backup rclone sync jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by (bucket) ((time()-label_replace(kube_job_status_completion_time{job_name=~\"rclone-sync-.*\"}, \"bucket\", \"$1\", \"job_name\", \"rclone-sync-(.*?)-(manual|[0-9-])*(manual|[0-9-])*\")))",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}