{
 "title": "Capacity Management Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "NodeGroup",
    "query": {
     "query": "label_values(kube_node_labels{cluster=~\"$cluster\"},label_elastisys_io_node_group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes with average CPU usage over 1h above threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (instance)(rate(node_cpu_seconds_total{mode!='idle',cluster=~'$cluster'}[1h])) / on (instance) instance:node_num_cpu:sum * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\") > 0.95)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes with average CPU usage over 24h above threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (instance)(rate(node_cpu_seconds_total{mode!='idle',cluster=~'$cluster'}[24h])) / on (instance) instance:node_num_cpu:sum * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\") > 0.75)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes with average Memory usage over 1h above threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg_over_time(instance:node_memory_utilisation:ratio{cluster=~'$cluster'}[1h]) * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\") > 0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes with average Memory usage over 24h above threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg_over_time(instance:node_memory_utilisation:ratio{cluster=~'$cluster'}[24h]) * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\") > 0.75)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Usage - $NodeGroup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "NodeGroup" },
  {
   "title": "Average CPU usage per Node over 1 hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!='idle',cluster='$cluster'}[1h])) / on (instance) instance:node_num_cpu:sum * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU usage per Node Group over 1 hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg((sum by (instance)(rate(node_cpu_seconds_total{mode!='idle',cluster='$cluster'}[1h])) / on (instance) instance:node_num_cpu:sum) * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\"))",
     "legendFormat": "$NodeGroup"
    }
   ]
  },
  {
   "title": "CPU usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance)(rate(node_cpu_seconds_total{mode!='idle',cluster='$cluster'}[$__rate_interval])) / on (instance) instance:node_num_cpu:sum) * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU usage per Node Group over 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg((sum by (instance)(rate(node_cpu_seconds_total{mode!='idle',cluster='$cluster'}[24h])) / on (instance) instance:node_num_cpu:sum) * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\"))",
     "legendFormat": "$NodeGroup"
    }
   ]
  },
  {
   "title": "CPU requested per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{cluster=~\"$cluster\", resource=\"cpu\"} and on (pod, namespace, cluster) kube_pod_info{cluster=~\"$cluster\"} and on (pod, namespace, cluster) kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\"} == 1 ) / sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\", resource=\"cpu\"}) * on (node) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Average CPU requested per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (node) (kube_pod_container_resource_requests{cluster=~\"$cluster\", resource=\"cpu\"} and on (pod, namespace, cluster) kube_pod_info{cluster=~\"$cluster\"} and on (pod, namespace, cluster) kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\"} == 1 ) / sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\", resource=\"cpu\"}) * on (node) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\"))",
     "legendFormat": "$NodeGroup"
    }
   ]
  },
  {
   "title": "CPU limits per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_limits{cluster=~\"$cluster\", resource=\"cpu\"} and on (pod, namespace, cluster) kube_pod_info{cluster=~\"$cluster\"} and on (pod, namespace, cluster) kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\"} == 1 ) / sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\", resource=\"cpu\"}) * on (node) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Memory Usage - $NodeGroup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "NodeGroup" },
  {
   "title": "Average Memory usage per Node over 1 hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(instance:node_memory_utilisation:ratio{cluster=~\"$cluster\"}[1h]) * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Memory usage per Node Group over 1 hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(instance:node_memory_utilisation:ratio{cluster=~\"$cluster\"}[1h]) * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\"))",
     "legendFormat": "$NodeGroup"
    }
   ]
  },
  {
   "title": "Memory usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{cluster=~\"$cluster\"} * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Memory usage per Node Group over 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(instance:node_memory_utilisation:ratio{cluster=~\"$cluster\"}[24h]) * on (instance) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\"))",
     "legendFormat": "$NodeGroup"
    }
   ]
  },
  {
   "title": "Memory requested per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{cluster=~\"$cluster\", resource=\"memory\"} and on (pod, namespace, cluster) kube_pod_info{cluster=~\"$cluster\"} and on (pod, namespace, cluster) kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\"} == 1 ) / sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\", resource=\"memory\"}) * on (node) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Average Memory requested per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (node) (kube_pod_container_resource_requests{cluster=~\"$cluster\", resource=\"memory\"} and on (pod, namespace, cluster) kube_pod_info{cluster=~\"$cluster\"} and on (pod, namespace, cluster) kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\"} == 1 ) / sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\", resource=\"memory\"}) * on (node) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\"))",
     "legendFormat": "$NodeGroup"
    }
   ]
  },
  {
   "title": "Memory limits per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_limits{cluster=~\"$cluster\", resource=\"memory\"} and on (pod, namespace, cluster) kube_pod_info{cluster=~\"$cluster\"} and on (pod, namespace, cluster) kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\"} == 1 ) / sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\", resource=\"memory\"}) * on (node) group_left (label_elastisys_io_node_group) label_replace(kube_node_labels{label_elastisys_io_node_group=~\"$NodeGroup\"}, \"instance\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}