{
 "title": "NetworkPolicy Dashboard Cilium",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(hubble_flows_processed_total,source_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Allowed packages going from pod",
   "type": "timeseries",
   "description": "Packets blocked by NetworkPolicy egress rules",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(hubble_flows_processed_total{type=\"PolicyVerdict\",verdict=\"FORWARDED\",traffic_direction=\"egress\",source_namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{source_pod}} - (to {{destination_pod}})"
    }
   ]
  },
  {
   "title": "Allowed packages going to pod",
   "type": "timeseries",
   "description": "Packets blocked by NetworkPolicy ingress rules",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(hubble_flows_processed_total{type=\"PolicyVerdict\",verdict=\"FORWARDED\",traffic_direction=\"ingress\",source_namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{source_pod}} - (to {{destination_pod}})"
    }
   ]
  },
  {
   "title": "Dropped packages going from pod",
   "type": "timeseries",
   "description": "Packets blocked by NetworkPolicy egress rules",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(hubble_drop_total{reason=\"POLICY_DENIED\",traffic_direction=\"egress\",source_namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{source_pod}} - (to {{destination_pod}})"
    }
   ]
  },
  {
   "title": "Dropped packages going to pod",
   "type": "timeseries",
   "description": "Packets blocked by NetworkPolicy ingress rules",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(hubble_drop_total{reason=\"POLICY_DENIED\",traffic_direction=\"ingress\",source_namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{source_pod}} - (from {{destination_pod}})"
    }
   ]
  }
 ]
}