{
 "title": "CisKubebench report",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(ciskubebench_scan,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n# CIS benchmarking tests, implemented by kube-bench\n\nThese tests are specified by CIS and implemented by kube-bench, see more information (such as descriptions of the different tests) about CIS [here](https://www.cisecurity.org/benchmark/kubernetes/) and kube-bench [here](https://github.com/aquasecurity/kube-bench).\n\nAutomatic vs manual tests: CIS have determined that some tests can be run automatically, kube-bench have additionally turned some manual tests into automatic ones. In this dashboard the manual tests (as per kube-bench) are only included in the table at the bottom.\n\nScored vs non-scored: scored tests are the test CIS chose as automatic, non-scored test are the manual tests that kube-bench made automatic. Non-scored might not fit as many kubernetes setups and are thus only classified as warnings if they fail.\n"
   }
  },
  {
   "title": "Number of tests reported: pass",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ciskubebench_scan{node=~\"$node\",score=\"pass\"})"
    }
   ]
  },
  {
   "title": "Number of tests reported: info",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ciskubebench_scan{node=~\"$node\",score=~\"info\"})"
    }
   ]
  },
  {
   "title": "Number of tests reported: warning",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ciskubebench_scan{node=~\"$node\",score=\"warn\"})"
    }
   ]
  },
  {
   "title": "Number of tests reported: fail",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ciskubebench_scan{node=~\"$node\",score=\"fail\"})"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ciskubebench_scan_tests{status=~\"WARN|FAIL\",node=~\"$node\"}"
    }
   ]
  }
 ]
}