{
 "title": "Cluster api",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(capi_cluster_info, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Cluster phase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Provisioned\"} == 1 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Provisioning\"} == 1) + 1 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Pending\"} == 1) + 2 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Unknown\"} == 1) + 3 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Deleting\"} == 1) + 4 or\n(capi_cluster_status_phase{name=~\"$cluster\", phase=\"Failed\"} == 1) + 5) without (instance, pod)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cluster paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(capi_cluster_spec_paused{name=~\"$cluster\"}) without (instance, pod)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cluster ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(capi_cluster_status_condition{name=~\"$cluster\", type=\"Ready\", status=\"True\"} == 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"Ready\", status=\"Unknown\"} == 1) + 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"Ready\", status=\"False\"} == 1) + 2) without (instance, pod)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Control plane initialized",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneInitialized\", status=\"True\"} == 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneInitialized\", status=\"Unknown\"} == 1) + 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneInitialized\", status=\"False\"} == 1) + 2) without (instance, pod)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Control plane ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneReady\", status=\"True\"} == 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneReady\", status=\"Unknown\"} == 1) + 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"ControlPlaneReady\", status=\"False\"} == 1) + 2) without (instance, pod)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Infrastructure ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(capi_cluster_status_condition{name=~\"$cluster\", type=\"InfrastructureReady\", status=\"True\"} == 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"InfrastructureReady\", status=\"Unknown\"} == 1) + 1 or (capi_cluster_status_condition{name=~\"$cluster\", type=\"InfrastructureReady\", status=\"False\"} == 1) + 2) without (instance, pod)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total control plane replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(capi_kubeadmcontrolplane_status_replicas{name=~\"${cluster}-control-plane\"}) without (instance, pod)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Unavailable control plane replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(capi_kubeadmcontrolplane_status_replicas_unavailable{name=~\"${cluster}-control-plane\"}) without (instance, pod)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Machine Deployment phase",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "capi_machinedeployment_status_phase{cluster_name=~\"$cluster\"} == 1",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Non running machine phase",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "capi_machine_status_phase{cluster_name=~\"$cluster\", phase!=\"Running\"} == 1",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Total control plane replicas",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(capi_machinedeployment_status_replicas{cluster_name=~\"$cluster\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MachineDeployment replicas with non True conditions",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "(capi_machine_status_condition{cluster_name=~\"$cluster\", name!~\".*control-plane.*\", status!=\"True\"} == 1) * on (name) group_left(node_name) capi_machine_status_noderef",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Control plane replicas with non True conditions",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "(capi_machine_status_condition{name=~\"${cluster}-control-plane.*\", status!=\"True\"} == 1) * on (name) group_left(node_name) capi_machine_status_noderef",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Unavailable MachineDeployment replicas",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(capi_machinedeployment_status_replicas_unavailable{cluster_name=~\"$cluster\"}) without (instance, pod)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Detailed graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Unavailable control plane replicas",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg(capi_kubeadmcontrolplane_status_replicas_unavailable{name=~\"${cluster}-control-plane\"}) without (instance, pod)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Non healthy machines",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "avg((capi_machine_status_condition{cluster_name=~\"$cluster\", type=\"NodeHealthy\", status!=\"True\"} == 1)  * on (name) group_left(node_name) capi_machine_status_noderef) by (cluster_name, node_name, status)",
     "legendFormat": "{{cluster_name}}: {{node_name}}"
    }
   ]
  },
  {
   "title": "Total MachineDeployment replicas",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "avg(capi_machinedeployment_status_replicas{cluster_name=~\"$cluster\"}) without (instance, pod)",
     "legendFormat": "{{cluster_name}}: {{name}}"
    }
   ]
  },
  {
   "title": "Unavailable MachineDeployment replicas",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "avg(capi_machinedeployment_status_replicas_unavailable{cluster_name=~\"$cluster\"}) without (instance, pod)",
     "legendFormat": "{{cluster_name}}: {{name}}"
    }
   ]
  }
 ]
}