{
 "title": "Simple Cluster Status Overview",
 "description": "Simple Cluster Status Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(probe_success, cluster)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success{cluster=~\"$cluster\"}, target)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Status",
   "type": "stat",
   "description": "Based on average probe success",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(cluster) (\n\tprobe_success{cluster=~\"$cluster\", target=~\"$target\"}\n)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Unready Pods by Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (phase)(\n\tkube_pod_status_phase{cluster=~\"$cluster\", namespace=~\"$namespace\", phase!=\"Succeeded\"} == 1\nand on (pod, namespace, cluster)\n\tkube_pod_status_ready{condition=\"true\", cluster=~\"$cluster\", namespace=~\"$namespace\"} == 0\n)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(max_over_time (\n\tprobe_success{cluster=~\"$cluster\", target=~\"$target\"}[24h]\n))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Global Probe Success",
   "type": "state-timeline",
   "description": "For more details, see [Prometheus Blackbox Exporter](/d/xtkCtBkiz/prometheus-blackbox-exporter)\n",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\",target=~\"$target\"}",
     "legendFormat": "{{ target }}"
    },
    {
     "expr": "sum (elasticsearch_cluster_health_status{color=\"green\"} or elasticsearch_cluster_health_status{color=\"yellow\"} * 0.5)"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "target",
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\",target=~\"$target\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{cluster=~\"$cluster\",target=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{cluster=~\"$cluster\",target=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{cluster=~\"$cluster\",target=~\"$target\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{cluster=~\"$cluster\",target=~\"$target\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{cluster=~\"$cluster\",target=~\"$target\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{cluster=~\"$cluster\",target=~\"$target\"} - time()",
     "legendFormat": "{{cluster}}",
     "orientation": "auto"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{cluster=~\"$cluster\",target=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{cluster=~\"$cluster\",target=~\"$target\"})"
    }
   ]
  }
 ]
}