{
 "title": "Cluster Autoscaler Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(capi_cluster_info,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Autoscaling enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_autoscaler_node_groups_count{pod=~\".*$cluster.*\", node_group_type=\"autoscaled\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{pod=~\".*$cluster.*\"})\n"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "gauge",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\", pod=~\".*$cluster.*\"})/sum(cluster_autoscaler_nodes_count{pod=~\".*$cluster.*\"})*100"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale{pod=~\".*$cluster.*\"})"
    }
   ]
  },
  {
   "title": "Number of unscheduled pods",
   "type": "stat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{pod=~\".*$cluster.*\"})",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"autoscaling\", pod=~\".*$cluster.*\"})"
    }
   ]
  },
  {
   "title": "Cluster scaling up/down or stable?",
   "type": "stat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cluster_autoscaler_scaled_up_nodes_total{pod=~\".*$cluster.*\"}[30m]))-sum(increase(cluster_autoscaler_scaled_down_nodes_total{pod=~\".*$cluster.*\"}[30m]))"
    }
   ]
  },
  {
   "title": "Pod activity",
   "type": "timeseries",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_evicted_pods_total{pod=~\".*$cluster.*\"})",
     "legendFormat": "evicted pods"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{pod=~\".*$cluster.*\"})",
     "legendFormat": "unscheduled pods"
    }
   ]
  },
  {
   "title": "Node activity",
   "type": "timeseries",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\", pod=~\".*$cluster.*\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\", pod=~\".*$cluster.*\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"notStarted\", pod=~\".*$cluster.*\"})\n",
     "legendFormat": "not started"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cluster_autoscaler_scaled_up_nodes_total{pod=~\".*$cluster.*\"}[5m])",
     "legendFormat": "scaled up total"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{pod=~\".*$cluster.*\"})",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{pod=~\".*$cluster.*\"})\n",
     "legendFormat": "total nodes"
    },
    {
     "expr": "sum(increase(cluster_autoscaler_scaled_down_nodes_total{pod=~\".*$cluster.*\"}[5m]))",
     "legendFormat": "scaled down total"
    }
   ]
  },
  {
   "title": "Unremovable nodes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "cluster_autoscaler_unremovable_nodes_count{pod=~\".*$cluster.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}