{
 "title": "Falco",
 "description": "Falco is a cloud-native security tool designed for Linux systems. It employs custom rules on kernel events, which are enriched with container and Kubernetes metadata, to provide real-time alerts. Falco helps you gain visibility into abnormal behavior, potential security threats, and compliance violations, contributing to comprehensive runtime security.",
 "tags": [
  "falco",
  "kubernetes",
  "security"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(falcosecurity_falco_cpu_usage_ratio,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(falcosecurity_falco_cpu_usage_ratio{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "source",
    "label": "source",
    "query": {
     "query": "label_values(falcosecurity_falco_rules_matches_total{namespace=~\"$namespace\", pod=~\"$pod\"},source)"
    }
   },
   {
    "name": "priority",
    "label": "priority",
    "query": {
     "query": "label_values(falcosecurity_falco_rules_matches_total{namespace=~\"$namespace\", source=~\"$source\"},priority)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(falcosecurity_falco_version_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Falco logs",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Detailed falco logs can be found in OpenSearch Dashboards:\n\n\n<<opensearchdashboardsURL>>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Rules",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(rule_name) (increase(falcosecurity_falco_rules_matches_total{cluster=~\"$cluster\", source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(source) (increase(falcosecurity_falco_rules_matches_total{cluster=~\"$cluster\", source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Priorities",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(priority) (increase(falcosecurity_falco_rules_matches_total{cluster=~\"$cluster\", source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "by Priority over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(priority) (increase(falcosecurity_falco_rules_matches_total{cluster=~\"$cluster\", source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Source over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(source) (increase(falcosecurity_falco_rules_matches_total{cluster=~\"$cluster\", source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Rule over time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(rule_name) (increase(falcosecurity_falco_rules_matches_total{cluster=~\"$cluster\", source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Scap events by instance over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_evts_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(falcosecurity_falco_n_evts_total[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(pod, raw_name) (falcosecurity_falco_memory_rss_bytes{cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory VSZ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(pod, raw_name) (falcosecurity_falco_memory_vsz_bytes{cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} - {{raw_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(pod) (falcosecurity_falco_cpu_usage_ratio{cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scap Drops total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Queue Drops",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(falcosecurity_falco_outputs_queue_num_drops_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scap Drops Buffer Enter",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"enter\", drop=\"clone_fork\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - clone_fork"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"enter\", drop=\"connect\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - connect"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"enter\", drop=\"dir_file\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - dir_file"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"enter\", drop=\"execve\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - execve"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"enter\", drop=\"open\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - open"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"enter\", drop=\"other_interest\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - other_interest"
    }
   ]
  },
  {
   "title": "Scap Drops Buffer Exit",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"exit\", drop=\"clone_fork\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - clone_fork"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"exit\", drop=\"connect\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - connect"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"exit\", drop=\"dir_file\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - dir_file"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"exit\", drop=\"execve\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - execve"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"exit\", drop=\"open\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - open"
    },
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_buffer_total{cluster=~\"$cluster\", pod=~\"$pod\", dir=\"exit\", drop=\"other_interest\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} - other_interest"
    }
   ]
  },
  {
   "title": "Scap Drops CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_cpu_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scap Drops Full Threadtable",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_full_threadtable_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scap Drops Scratch Map",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(falcosecurity_scap_n_drops_scratch_map_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Fleet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Versions",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 115 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(version) (falcosecurity_falco_version_info{cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engines",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 115 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(engine_name) (falcosecurity_scap_engine_name_info{cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}