{
 "title": "Fluentd 1.x",
 "description": "fluentd 1.x deployed in kubernetes and scraped by prometheus",
 "tags": [
  "fluentd",
  "logging"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\".*fluentd.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluentd output error/retry rate",
   "type": "timeseries",
   "description": "If you see errors then you probably have serious issues with log processing, see https://docs.fluentd.org/buffer#handling-unrecoverable-errors\n\nRetries are normal but should occur only from time to time, otherwise check for network errors or destination is too slow and requires additional tuning per given provider.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "Retry rate"
    },
    {
     "expr": "sum(rate(fluentd_output_status_num_errors{pod=~\"$pod\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Input /  output rate",
   "type": "timeseries",
   "description": "Input  and output total rates",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total{pod=~\"$pod\"}[1m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(fluentd_output_status_write_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "fluentd output status buffer available space ratio",
   "type": "timeseries",
   "description": "This should not reach 0 otherwise logs are blocked from processing or even dropped",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(fluentd_output_status_buffer_available_space_ratio)",
     "legendFormat": "lowest across all hosts"
    }
   ]
  },
  {
   "title": "fluentd output status flush time count rate",
   "type": "timeseries",
   "description": "total flush time",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_flush_time_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "time"
    },
    {
     "expr": "sum(rate(fluentd_output_status_slow_flush_count[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Current total size of stage and queue buffers.",
   "type": "timeseries",
   "description": "Current total size of stage and queue buffers.\nfluentd_output_status_buffer_total_bytes",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_total_bytes) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd output buffer queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_queue_length)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Input details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Input entries rate (total)",
     "type": "timeseries",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total{pod=~\"$pod\"}[1m])) ",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Input entries rate per hostname",
     "type": "timeseries",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total{pod=~\"$pod\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Input entries rate per namespace",
     "type": "timeseries",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total{pod=~\"$pod\"}[1m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Input entries rate per instance",
     "type": "timeseries",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total{pod=~\"$pod\"}[1m])) by (instance)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Input details (warning, very slow!)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Input entries rate per tag",
     "type": "timeseries",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total{pod=~\"$pod\"}[1m])) by (tag)",
       "legendFormat": "{{tag}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Stage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current length of stage buffers.",
     "type": "timeseries",
     "description": "fluentd_output_status_buffer_stage_length",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_stage_length) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    },
    {
     "title": "Current total size of stage buffers.",
     "type": "timeseries",
     "description": "fluentd_output_status_buffer_stage_byte_size",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_stage_byte_size) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Maximum buffer length in last 1min",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_queue_length[1m])",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    },
    {
     "title": "Maximum buffer bytes in last 1min",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_total_bytes[1m])",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    },
    {
     "title": "Current length of queue buffers.",
     "type": "timeseries",
     "description": "fluentd_output_status_buffer_queue_length",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_queue_length) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    },
    {
     "title": "Current total size of queue buffers.",
     "type": "timeseries",
     "description": "fluentd_output_status_queue_byte_size",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(fluentd_output_status_queue_byte_size) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ratio of available space in buffer.",
     "type": "timeseries",
     "description": "fluentd_output_status_buffer_available_space_ratio",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_available_space_ratio) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Retries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current retry counts.",
     "type": "timeseries",
     "description": "fluentd_output_status_retry_count",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_retry_count{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current emit records",
     "type": "timeseries",
     "description": "fluentd_output_status_emit_records",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_records{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current emit counts rate",
     "type": "timeseries",
     "description": "fluentd_output_status_emit_count",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_count{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current rollback counts",
     "type": "timeseries",
     "description": "fluentd_output_status_rollback_count",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_rollback_count{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current write counts",
     "type": "timeseries",
     "description": "fluentd_output_status_write_count",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_write_count{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current slow flush counts",
     "type": "timeseries",
     "description": "fluentd_output_status_slow_flush_count",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_slow_flush_count{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Current retry wait",
     "type": "timeseries",
     "description": "fluentd_output_status_retry_wait",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_retry_wait{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total flush time",
     "type": "timeseries",
     "description": "fluentd_output_status_flush_time_count",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_flush_time_count{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current number of errors rate",
     "type": "timeseries",
     "description": "fluentd_output_status_num_errors",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_num_errors{pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer timekeys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Timekey diff",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fluentd_output_status_buffer_newest_timekey - fluentd_output_status_buffer_oldest_timekey",
       "legendFormat": "{{pod}} {{ type}}"
      }
     ]
    },
    {
     "title": "Newest timekey in buffer.",
     "type": "timeseries",
     "description": "fluentd_output_status_buffer_newest_timekey",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_newest_timekey) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    },
    {
     "title": "Oldest timekey in buffer.",
     "type": "timeseries",
     "description": "fluentd_output_status_buffer_oldest_timekey",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_oldest_timekey) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    }
   ]
  }
 ]
}