{
 "title": "Gatekeeper",
 "description": "Visualize violations from OPA Gatekeeper and OPA Scorecard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gatekeeper logs",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Detailed gatekeeper logs can be found in OpenSearch Dashboards:\n\n\n<<opensearchdashboardsURL>>"
   }
  },
  {
   "title": "Audit process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Violations",
   "type": "bargauge",
   "description": "The number of audit violations per constraint detected in the last audit cycle",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (enforcement_action) (gatekeeper_violations{cluster=~\"$cluster\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Audit duration",
   "type": "stat",
   "description": "Latency of audit operation",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gatekeeper_audit_duration_seconds_count{cluster=~\"$cluster\"}[10m])"
    }
   ]
  },
  {
   "title": "Audit last run time",
   "type": "stat",
   "description": "Description: Timestamp of last audit run time",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - gatekeeper_audit_last_run_time{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total GroupVersionKinds",
   "type": "stat",
   "description": "Total number of watched GroupVersionKinds",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_watch_manager_watched_gvk{cluster=~\"$cluster\", pod=~\"gatekeeper-controller.+\"}) / sum(gatekeeper_watch_manager_watched_gvk{cluster=~\"$cluster\", pod=~\"gatekeeper-controller.+\"})"
    }
   ]
  },
  {
   "title": "Total GroupVersionKinds registered",
   "type": "stat",
   "description": "Total number of GroupVersionKinds with a registered watch intent",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_watch_manager_intended_watch_gvk{cluster=~\"$cluster\", pod=~\"gatekeeper-controller.+\"}) / sum(gatekeeper_watch_manager_intended_watch_gvk{cluster=~\"$cluster\", pod=~\"gatekeeper-controller.+\"})"
    }
   ]
  },
  {
   "title": "Admission webook",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mutation request count",
   "type": "timeseries",
   "description": "Description: The number of requests that are routed to mutation webhook",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (mutation_status, pod) (rate(gatekeeper_mutation_request_count_total{cluster=~\"$cluster\"}[20m]))",
     "legendFormat": "{{mutation_status}}"
    }
   ]
  },
  {
   "title": "Validation request count",
   "type": "timeseries",
   "description": "Description: The number of requests that are routed to validation webhook",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (admission_status, pod) (rate(gatekeeper_validation_request_count_total{cluster=~\"$cluster\"}[20m]))",
     "legendFormat": "{{admission_status}}"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Constraint templates",
   "type": "stat",
   "description": "Description: Current number of constraint templates\n\nUnderstanding this metric: Gatekeeper subscribes to a watch on all ConstraintTemplate resources. Whenever one is created or deleted on the cluster, this count gets updated.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (gatekeeper_constraint_templates{cluster=~\"$cluster\", pod=~\"gatekeeper-audit-.*\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Constraints",
   "type": "bargauge",
   "description": "Current number of constraints\nUnderstanding this metric: Gatekeeper subscribes to a watch on all constraint resources. Whenever one is created or deleted on the cluster, this count gets updated.",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(enforcement_action) (gatekeeper_constraints{cluster=~\"$cluster\", pod=~\"gatekeeper-audit-.*\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}