{
 "title": "NetworkPolicy Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(no_policy_drop_counter,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(no_policy_drop_counter,pod_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Packets allowed by NetworkPolicy going from pod",
   "type": "timeseries",
   "description": "Packets blocked by NetworkPolicy egress rules",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(policy_accept_counter{type=\"fw\",cluster=~\"$cluster\",pod_namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{exported_pod}} - {{policy}}"
    }
   ]
  },
  {
   "title": "Packets allowed by NetworkPolicy going to pod",
   "type": "timeseries",
   "description": "Packets blocked by NetworkPolicy ingress rules",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(policy_accept_counter{type=\"tw\",cluster=~\"$cluster\",pod_namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{exported_pod}} - {{policy}}"
    }
   ]
  },
  {
   "title": "Dropped packets going from pod",
   "type": "timeseries",
   "description": "Packets blocked by NetworkPolicy egress rules",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(no_policy_drop_counter{type=\"fw\",cluster=~\"$cluster\",pod_namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Dropped packets going to pod",
   "type": "timeseries",
   "description": "Packets blocked by NetworkPolicy ingress rules",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(no_policy_drop_counter{type=\"tw\",cluster=~\"$cluster\",pod_namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  }
 ]
}