{
 "title": "DNS Metrics",
 "description": "A dashboard for the CoreDNS NodeLocalDNS server.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(coredns_build_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "up{job=\"${job}\",cluster=~\"${cluster}\"}"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(coredns_dns_request_size_bytes_count, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_count{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_count{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_count{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_count{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (DO bit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_do_count_total{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "DO"
    },
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_count{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (size, udp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Requests (size, tcp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses (by rcode)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Responses (size, udp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses (size, tcp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (le, proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Cache (size)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (type)",
     "legendFormat": "hits:{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[5m])) by (type)",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}