{
 "title": "Read and Write - Namespace (Pods with PVCs)",
 "description": "See the write and read throughput and IOPS for different pods with connected PVCs filtered by namespace",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\"}[5m])) by (pod, namespace)\n)\n* on(pod, namespace) group_left()\n(\n  group by(pod, namespace) (kube_pod_spec_volumes_persistentvolumeclaims_info)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_fs_writes_total{namespace=~\"$namespace\"}[5m])) by (pod, namespace)\n)\n* on(pod, namespace) group_left()\n(\n  group by(pod, namespace) (kube_pod_spec_volumes_persistentvolumeclaims_info)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\"}[5m])) by (pod, namespace)\n)\n* on(pod, namespace) group_left()\n(\n  group by(pod, namespace) (kube_pod_spec_volumes_persistentvolumeclaims_info)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_fs_reads_total{namespace=~\"$namespace\"}[5m])) by (pod, namespace)\n)\n* on(pod, namespace) group_left()\n(\n  group by(pod, namespace) (kube_pod_spec_volumes_persistentvolumeclaims_info)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}