{
 "title": "Velero Stats",
 "description": "Stats for Velero backups",
 "tags": [ "velero" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(velero_backup_attempt_total, cluster)"
   },
   {
    "name": "schedule",
    "query": "label_values(velero_backup_attempt_total, schedule)"
   }
  ]
 },
 "panels": [
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hours since last Backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule!=\"\", cluster=~\"$cluster\"}) / 60 / 60",
     "legendFormat": "{{schedule}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}) by (cluster) / sum(velero_backup_attempt_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Active Backup",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_active_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Backup Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "velero_backup_total{cluster=~\"$cluster\"}",
     "legendFormat": "Backup Total - {{cluster}}"
    },
    {
     "expr": "velero_backup_active_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}",
     "legendFormat": "Backup {{schedule}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Backup Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])) by (le, cluster))",
     "legendFormat": "Scheduled: 0.99 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(velero_backup_duration_seconds_bucket{schedule!~\".*\", cluster=~\"$cluster\"}[15m])) by (le, cluster))",
     "legendFormat": "Non Scheduled: 0.99 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])) by (le, cluster))",
     "legendFormat": "Scheduled: 0.95 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(velero_backup_duration_seconds_bucket{schedule!~\".*\", cluster=~\"$cluster\"}[15m])) by (le, cluster))",
     "legendFormat": "Non Scheduled: 0.95 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])) by (le, cluster))",
     "legendFormat": "Scheduled: 0.50 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(velero_backup_duration_seconds_bucket{schedule!~\".*\", cluster=~\"$cluster\"}[15m])) by (le, cluster))",
     "legendFormat": "Non Scheduled: 0.50 - {{cluster}}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(velero_backup_tarball_size_bytes{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "{{schedule}} -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_backup_tarball_size_bytes{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Non Scheduled -  {{cluster}}"
    }
   ]
  },
  {
   "title": "Backup per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup success -  {{cluster}}"
    },
    {
     "expr": "sum(increase(velero_backup_failure_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup failure -  {{cluster}}"
    },
    {
     "expr": "sum(increase(velero_backup_partial_failure_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup partial failure -  {{cluster}}"
    },
    {
     "expr": "sum(increase(velero_backup_deletion_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup deletion success -  {{cluster}}"
    },
    {
     "expr": "sum(increase(velero_backup_deletion_failure_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[1h])) by (cluster)",
     "legendFormat": "Backup deletion failure -  {{cluster}}"
    }
   ]
  },
  {
   "title": "Restore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Restore",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(velero_restore_attempt_total{cluster=~\"$cluster\"}[$__interval])) by (cluster) / sum(rate(velero_restore_success_total{cluster=~\"$cluster\"}[$__interval])) by (cluster)",
     "legendFormat": " {{cluster}}"
    }
   ]
  },
  {
   "title": "Restore Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(velero_restore_success_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])) by (cluster) / sum(rate(velero_restore_attempt_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])) by (cluster)",
     "legendFormat": "Backup success rate -  {{cluster}}"
    },
    {
     "expr": "sum(rate(velero_restore_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])) by (cluster) / sum(rate(velero_restore_attempt_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])) by (cluster)",
     "legendFormat": "Backup success rate {{schedule}} -  {{cluster}}"
    }
   ]
  },
  {
   "title": "Total Restore Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(velero_restore_total{cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Total -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_success_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Success Total {{schedule}} -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_success_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Success Total -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_partial_failure_total{schedule=~\"$schedule\"}[15m])",
     "legendFormat": " Restore Partial Failure Total {{schedule}} -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_partial_failure_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Partial Failure Total -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_failed_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Failure Total {{schedule}} -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_failed_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Failure Total -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_validation_failed_total{schedule=~\"$schedule\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Validation Failed {{schedule}} -  {{cluster}}"
    },
    {
     "expr": "avg_over_time(velero_restore_validation_failed_total{schedule!~\".*\", cluster=~\"$cluster\"}[15m])",
     "legendFormat": "Restore Validation Failed -  {{cluster}}"
    }
   ]
  }
 ]
}