$schema: https://json-schema.org/draft/2020-12/schema
# TODO point to main branch before merge
$id: https://github.com/elastisys/compliantkubernetes-apps/raw/ka/jsonschema/config/schemas/config.yaml
title: Compliant Kubernetes Apps settings
description: |
  This describes the structure of the configuration for both the service
  cluster and the workload cluster, but keep in mind that each configuration
  file will contain different settings.
$defs:
  $comment: |
    Location for common types of things for reuse with a reference like

    ```yaml
    thing:
      $ref: "#/$defs/thing"
    ```
  affinity:
    $comment: Real k8s resources might have existing schemas that could be reused as-is
    additionalProperties: false
    default:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    properties:
      podAntiAffinity:
        additionalProperties: false
        properties:
          preferredDuringSchedulingIgnoredDuringExecution:
            items:
              additionalProperties: false
              properties:
                podAffinityTerm:
                  additionalProperties: false
                  properties:
                    labelSelector:
                      additionalProperties: false
                      properties:
                        matchExpressions:
                          items:
                            additionalProperties: false
                            properties:
                              key:
                                default: app.kubernetes.io/instance
                                type: string
                              operator:
                                default: In
                                type: string
                              values:
                                items:
                                  default: opensearch-master
                                  type: string
                                type: array
                            type: object
                          type: array
                      type: object
                    topologyKey:
                      default: kubernetes.io/hostname
                      type: string
                  type: object
                weight:
                  default: 1
                  type: number
              type: object
            type: array
          requiredDuringSchedulingIgnoredDuringExecution:
            items:
              additionalProperties: false
              properties:
                labelSelector:
                  additionalProperties: false
                  properties:
                    matchExpressions:
                      items:
                        additionalProperties: false
                        properties:
                          key:
                            default: app
                            type: string
                          operator:
                            default: In
                            type: string
                          values:
                            items:
                              default: harbor
                              type: string
                            type: array
                        type: object
                      type: array
                  type: object
                topologyKey:
                  default: kubernetes.io/hostname
                  type: string
              type: object
            type: array
        type: object
    title: Affinity
    type: object
  commonResource:
    additionalProperties: false
    description: This is meant to describe the base class if you will, for ck8s resources.
    properties:
      affinity:
        $ref: '#/$defs/affinity'
      enabled:
        type: boolean
      nodeSelector:
        $ref: '#/$defs/nodeSelector'
      resources:
        $ref: '#/$defs/resources'
      tolerations:
        $ref: '#/$defs/tolerations'
      topologySpreadConstraints:
        $ref: '#/$defs/topologySpreadConstraints'
    required:
      - enabled
    title: Common Resource
    type: object
  cpumem:
    additionalProperties: false
    properties:
      cpu:
        default: 100m
        pattern: ^[1-9][0-9]*m?$
        type:
          - string
          - integer
      memory:
        default: 128Mi
        pattern: ^[0-9]+(\.[0-9]+)?([KMG]i)?$
        type:
          - string
          - integer
    title: CPU and Memory specifications
    type: object
  extraArgs:
    description: Additional arguments for a thing???
    items:
      type: string
    title: Extra arguments
    type: array
  fluentdBuffer:
    additionalProperties:
      $comment: Assuming that these are never structures, only scalars
      not:
        type:
          - object
          - array
      type:
        - string
        - integer
        - boolean
    properties:
      chunkLimitSize:
        examples:
          - 50MB
        type: string
      flushInterval:
        examples:
          - 15m
        type: string
      flushMode:
        examples:
          - interval
        type: string
      flushThreadBurstInterval:
        type: number
      flushThreadCount:
        type: integer
      retryForever:
        type: boolean
      retryMaxInterval:
        type: integer
      retryType:
        examples:
          - exponential_backoff
        type: string
      timekey:
        examples:
          - 10m
        type: string
      timekeyUseUtc:
        type: boolean
      timekeyWait:
        examples:
          - 1m
        type: string
      totalLimitSize:
        examples:
          - 9GB
        type: string
    type: object
  goDuration:
    examples:
      - 2h45m0s
    pattern: ^([-+]?[0-9]+(.[0-9]+)?(ns|us|µs|ms|s|m|h))+$
    title: A more complexly expressed amount of time
    type: string
  iplist:
    items:
      oneOf:
        - format: ipv4
        - format: ipv6
        - format: netmask
      type: string
    type: array
  listen:
    additionalProperties: false
    properties:
      ips:
        $ref: '#/$defs/iplist'
      ports:
        $ref: '#/$defs/portlist'
    type: object
  nodeSelector:
    additionalProperties:
      type: string
    examples:
      - kubernetes.io/os: linux
    type: object
  pct:
    description: Percentage, 0% - 100%
    maximum: 100
    minimum: 0
    title: Percentage
    type: number
  portlist:
    items:
      maximum: 65535
      minimum: 1
      type: integer
    type: array
  resources:
    additionalProperties: false
    properties:
      limits:
        $ref: '#/$defs/cpumem'
      requests:
        $ref: '#/$defs/cpumem'
    type: object
  timeRange:
    examples:
      - 300s
      - 72h
      - 3dd
    pattern: ^[0-9]+[hmsd]+$
    title: An amount of time
    type: string
  tolerations:
    items:
      additionalProperties: false
      properties:
        effect:
          examples:
            - NoExecute
            - NoSchedule
            - PreferNoSchedule
          type: string
        key:
          examples:
            - node.kubernetes.io/memory-pressure
            - node.kubernetes.io/not-ready
            - node.kubernetes.io/unreachable
            - node-role.kubernetes.io/control-plane
            - node-role.kubernetes.io/master
          type: string
        operator:
          examples:
            - Exists
          type: string
        tolerationSeconds:
          type: integer
        value:
          type: string
      type: object
    type: array
  topologySpreadConstraints:
    items:
      additionalProperties: false
      properties:
        labelSelector:
          additionalProperties: false
          properties:
            matchLabels:
              additionalProperties:
                type: string
              properties: {}
              type: object
          type: object
        maxSkew:
          default: 1
          type: number
        topologyKey:
          default: kubernetes.io/hostname
          type: string
        whenUnsatisfiable:
          default: DoNotSchedule
          type: string
      type: object
    type: array
type: object
required:
  - global
properties:
  global:
    title: Global options
    description: Some common options used in various helm charts.
    type: object
    required:
      - ck8sVersion
      - ck8sCloudProvider
      - ck8sEnvironmentName
      - ck8sFlavor
      - baseDomain
      - opsDomain
    properties:
      ck8sVersion:
        title: Compliant Kubernetes Apps version
        description: |-
          Use version number if you are exactly at a release tag.
          Otherwise use full commit hash of current commit.
          `any`, can be used to disable this validation.
        type: string
        examples:
          - v0.42.1
          - any
          - 424442541a567646c232d949bad1af2b5b7cb885
      ck8sCloudProvider:
        type: string
        enum:
          - aws
          - baremetal
          - citycloud
          - elastx
          - exoscale
          - none
          - safespring
          - upcloud
      ck8sEnvironmentName:
        title: Environment name
        type: string
        examples:
          - my-ck8s-cluster
      ck8sFlavor:
        type: string
        enum:
          - prod
          - dev
          - air-gapped
      baseDomain:
        title: Base Domain
        description: |-
          Domain intended for ingress usage in the workload cluster
          and to reach application developer facing services such as Grafana, Harbor and OpenSearch Dashboards.
          E.g. with 'prod.domain.com', OpenSearch Dashboards is reached via 'opensearch.prod.domain.com'.
        type: string
        format: hostname
      opsDomain:
        description: |-
          Domain intended for ingress usage in the service cluster and to reach
          non-user facing services such as Thanos and OpenSearch.
          E.g. with 'ops.prod.domain.com', OpenSearch is reached via 'opensearch.ops.prod.domain.com'.
        type: string
        format: hostname
      scDomain:
        description: If baseDomain for wc and sc are not the same, set the domain of the sc cluster.
        type: string
        oneOf: # Templates do not handle missing values so they must be empty strings to disable. Future FIXME?
          - const: ""
          - format: hostname
      scOpsDomain:
        description: If opsDomain for wc and sc are not the same, set the ops domain of the sc cluster.
        type: string
        oneOf:
          - const: ""
          - format: hostname
      issuer:
        description: |-
          Default cert-manager issuer to use for issuing certificates for ingresses.
          Normally one of `letsencrypt-staging` or `letsencrypt-prod`.
        type: string
        default: letsencrypt-staging
        enum:
          - letsencrypt-staging
          - letsencrypt-prod
      verifyTls:
        description: Verify ingress certificates
        type: boolean
        default: true
      clusterDns:
        description: IP of the cluster DNS in kubernetes
        type: string
        default: 10.233.0.3
        format: ip-address
      clusterName:
        type: string
      clustersMonitoring:
        description: |-
          Names of the workload clusters that sends metrics to this cluster.
          Mainly used for filtering of metrics.
        type: array
        items:
          type: string
          pattern: -[sw]c$
      containerRuntime:
        title: Container runtime
        default: containerd
        type: string
        enum:
          - containerd
          - docker
    additionalProperties: false
  clusterApi:
    additionalProperties: false
    properties:
      clusters:
        items:
          type: string
        type: array
      enabled:
        default: false
        type: boolean
      monitoring:
        additionalProperties: false
        properties:
          enabled:
            default: false
            type: boolean
        type: object
    type: object
  user:
    additionalProperties:
      $ref: '#/$defs/commonResource'
    properties:
      alertmanager:
        additionalProperties:
          $ref: '#/$defs/commonResource'
        properties:
          adminGroups:
            items:
              type: string
            type: array
          adminUsers:
            items:
              type: string
            type: array
          enabled:
            default: true
            type: boolean
          ingress:
            additionalProperties: false
            properties:
              enabled:
                default: false
                type: boolean
            type: object
          serviceAccounts:
            items:
              type: string
            type: array
        type: object
      constraints:
        additionalProperties:
          additionalProperties:
            properties: {}
            type: object
          properties: {}
          propertyNames:
            title: Service name
            type: string
          type: object
        description: |-
          Any namespace listed in constraints are exempted from HNC managed namespaces
          This to override the Pod Security Admission level
          Example of constraint can be found here: helmfile.d/charts/gatekeeper/podsecuritypolicies/values.yaml
          The only extra label "psaLevel: <baseline/privileged>" is shown in the following example:
          <namespace>:
            psaLevel: <baseline/privileged>
            <service-name>:
              ...
        properties: {}
        propertyNames:
          title: Namespace
          type: string
        type: object
      createNamespaces:
        type: boolean
      grafanaPassword:
        type: string
      namespaces:
        items:
          examples:
            - production
            - staging
          type: string
        type: array
    type: object
additionalProperties:
  type: object
  properties: {}
