$schema: https://json-schema.org/draft/2020-12/schema
# TODO point to main branch before merge
$id: https://github.com/elastisys/compliantkubernetes-apps/raw/ka/jsonschema/config/schemas/config.yaml
title: Compliant Kubernetes Apps settings
description: |
  This describes the structure of the configuration for both the service
  cluster and the workload cluster, but keep in mind that each configuration
  file will contain different settings.
$defs:
  $comment: |
    Location for common types of things for reuse with a reference like

    ```yaml
    thing:
      $ref: "#/$defs/thing"
    ```
type: object
required:
  - global
properties:
  global:
    title: Global options
    description: Some common options used in various helm charts.
    type: object
    required:
      - ck8sVersion
      - ck8sCloudProvider
      - ck8sEnvironmentName
      - ck8sFlavor
      - baseDomain
      - opsDomain
    properties:
      ck8sVersion:
        title: Compliant Kubernetes Apps version
        description: |-
          Use version number if you are exactly at a release tag.
          Otherwise use full commit hash of current commit.
          `any`, can be used to disable this validation.
        type: string
        examples:
          - v0.42.1
          - any
          - 424442541a567646c232d949bad1af2b5b7cb885
      ck8sCloudProvider:
        type: string
        enum:
          - aws
          - baremetal
          - citycloud
          - elastx
          - exoscale
          - none
          - safespring
          - upcloud
      ck8sEnvironmentName:
        title: Environment name
        type: string
        examples:
          - my-ck8s-cluster
      ck8sFlavor:
        type: string
        enum:
          - prod
          - dev
          - air-gapped
      baseDomain:
        title: Base Domain
        description: |-
          Domain intended for ingress usage in the workload cluster
          and to reach application developer facing services such as Grafana, Harbor and OpenSearch Dashboards.
          E.g. with 'prod.domain.com', OpenSearch Dashboards is reached via 'opensearch.prod.domain.com'.
        type: string
        format: hostname
      opsDomain:
        description: |-
          Domain intended for ingress usage in the service cluster and to reach
          non-user facing services such as Thanos and OpenSearch.
          E.g. with 'ops.prod.domain.com', OpenSearch is reached via 'opensearch.ops.prod.domain.com'.
        type: string
        format: hostname
      scDomain:
        description: If baseDomain for wc and sc are not the same, set the domain of the sc cluster.
        type: string
        oneOf: # Templates do not handle missing values so they must be empty strings to disable. Future FIXME?
          - const: ""
          - format: hostname
      scOpsDomain:
        description: If opsDomain for wc and sc are not the same, set the ops domain of the sc cluster.
        type: string
        oneOf:
          - const: ""
          - format: hostname
      issuer:
        description: |-
          Default cert-manager issuer to use for issuing certificates for ingresses.
          Normally one of `letsencrypt-staging` or `letsencrypt-prod`.
        type: string
        default: letsencrypt-staging
        enum:
          - letsencrypt-staging
          - letsencrypt-prod
      verifyTls:
        description: Verify ingress certificates
        type: boolean
        default: true
      clusterDns:
        description: IP of the cluster DNS in kubernetes
        type: string
        default: 10.233.0.3
        format: ip-address
      clusterName:
        type: string
      clustersMonitoring:
        description: |-
          Names of the workload clusters that sends metrics to this cluster.
          Mainly used for filtering of metrics.
        type: array
        items:
          type: string
          pattern: -[sw]c$
      containerRuntime:
        title: Container runtime
        default: containerd
        type: string
        enum:
          - containerd
          - docker
    additionalProperties: false
  alerts:
    additionalProperties: false
    properties:
      alertTo:
        type: string
      customReceivers:
        type: array
      opsGenie:
        additionalProperties: false
        properties:
          apiUrl:
            default: https://api.eu.opsgenie.com
            format: uri
            type: string
        type: object
      opsGenieHeartbeat:
        additionalProperties: false
        if:
          properties:
            enabled:
              const: true
        properties:
          enabled:
            default: false
            type: boolean
          name:
            type: string
          url:
            default: https://api.eu.opsgenie.com/v2/heartbeats
            format: uri
            type: string
        required:
          - enabled
        then:
          required:
            - name
        type: object
      slack:
        additionalProperties: false
        properties:
          channel:
            type: string
          customTemplate:
            type: object
        type: object
    type: object
  grafana:
    additionalProperties: false
    properties:
      ops:
        additionalProperties: false
        properties:
          additionalConfigValues:
            type: object
          additionalDatasources:
            type: object
          affinity:
            $ref: '#/$defs/affinity'
          enabled:
            default: true
            type: boolean
          nodeSelector:
            $ref: '#/$defs/nodeSelector'
          oidc:
            additionalProperties: false
            properties:
              allowedDomains:
                items:
                  type: string
                type: array
              enabled:
                default: true
                type: boolean
              scopes:
                default: openid profile email groups
                type: string
              userGroups:
                additionalProperties: false
                properties:
                  grafanaAdmin:
                    default: grafana_admin
                    type: string
                  grafanaEditor:
                    default: grafana_editor
                    type: string
                  grafanaViewer:
                    default: grafana_viewer
                    type: string
                type: object
            type: object
          plugins:
            type: array
          resources:
            $ref: '#/$defs/resources'
          sidecar:
            additionalProperties: false
            properties:
              resources:
                $ref: '#/$defs/resources'
            type: object
          subdomain:
            default: grafana
            type: string
          tolerations:
            $ref: '#/$defs/tolerations'
          trailingDots:
            default: true
            type: boolean
          viewersCanEdit:
            default: true
            type: boolean
        type: object
      user:
        $ref: '#/properties/grafana/properties/ops'
    type: object
  grafanaLabelEnforcer:
    additionalProperties: false
    properties:
      resources:
        $ref: '#/$defs/resources'
    type: object
  kubeStateMetrics:
    additionalProperties: false
    properties:
      clusterAPIMetrics:
        additionalProperties: false
        properties:
          enabled:
            default: false
            type: boolean
        type: object
      resources:
        $ref: '#/$defs/resources'
    type: object
  metricsServer:
    additionalProperties: false
    properties:
      enabled:
        default: true
        type: boolean
      resources:
        $ref: '#/$defs/resources'
    type: object
  openstackMonitoring:
    additionalProperties: false
    properties:
      enabled:
        default: false
        type: boolean
    type: object
  prometheus:
    additionalProperties: false
    properties:
      affinity:
        $ref: '#/$defs/affinity'
      alertmanagerSpec:
        additionalProperties: false
        properties:
          groupBy:
            items:
              default: '...'
              type: string
            type: array
          replicas:
            default: 2
            type: number
          resources:
            $ref: '#/$defs/resources'
          storage:
            additionalProperties: false
            properties:
              volumeClaimTemplate:
                additionalProperties: false
                properties:
                  spec:
                    additionalProperties: false
                    properties:
                      accessModes:
                        items:
                          default: ReadWriteOnce
                          type: string
                        type: array
                      resources:
                        $ref: '#/$defs/resources'
                    type: object
                type: object
            type: object
          topologySpreadConstraints:
            $ref: '#/$defs/topologySpreadConstraints'
        type: object
      capacityManagementAlerts:
        additionalProperties: false
        properties:
          disklimit:
            default: 75
            type: number
          enabled:
            default: true
            type: boolean
          persistentVolume:
            additionalProperties: false
            properties:
              enabled:
                default: true
                type: boolean
              limit:
                default: 75
                type: number
            type: object
          requestlimit:
            additionalProperties: false
            properties:
              cpu:
                items:
                  additionalProperties: false
                  properties:
                    limit:
                      examples:
                        - 80
                      type: number
                    name:
                      examples:
                        - worker
                        - elastisys
                      type: string
                    pattern:
                      examples:
                        - .*-worker-.*
                        - .*-elastisys-.*
                      type: string
                  type: object
                type: array
              memory:
                items:
                  additionalProperties: false
                  properties:
                    limit:
                      examples:
                        - 80
                      type: number
                    name:
                      default: worker
                      type: string
                    pattern:
                      default: .*-worker-.*
                      type: string
                  type: object
                type: array
            type: object
          usagelimit:
            default: 95
            type: number
        type: object
      diskAlerts:
        additionalProperties: false
        properties:
          inode:
            additionalProperties: false
            properties:
              predictLinear:
                items:
                  additionalProperties: false
                  properties:
                    for:
                      $ref: '#/$defs/timeRange'
                      default: 1h
                    freeSpacePercentage:
                      $ref: '#/$defs/pct'
                      default: 40
                    hours:
                      default: 24
                      type: number
                    pattern:
                      additionalProperties: false
                      properties:
                        exclude:
                          additionalProperties: false
                          properties:
                            disk:
                              default: ""
                              type: string
                            node:
                              default: ""
                              type: string
                          type: object
                        include:
                          additionalProperties: false
                          properties:
                            disk:
                              default: .*
                              type: string
                            node:
                              default: .*
                              type: string
                          type: object
                      type: object
                    severity:
                      default: warning
                      type: string
                  type: object
                type: array
              space:
                items:
                  additionalProperties: false
                  properties:
                    for:
                      $ref: '#/$defs/timeRange'
                      default: 1h
                    freeSpacePercentage:
                      $ref: '#/$defs/pct'
                      default: 5
                    pattern:
                      additionalProperties: false
                      properties:
                        exclude:
                          additionalProperties: false
                          properties:
                            disk:
                              default: ""
                              type: string
                            node:
                              default: ""
                              type: string
                          type: object
                        include:
                          additionalProperties: false
                          properties:
                            disk:
                              default: .*
                              type: string
                            node:
                              default: .*
                              type: string
                          type: object
                      type: object
                    severity:
                      default: warning
                      type: string
                  type: object
                type: array
            type: object
          perf:
            type: boolean
          storage:
            additionalProperties: false
            properties:
              predictLinear:
                items:
                  additionalProperties: false
                  properties:
                    for:
                      $ref: '#/$defs/timeRange'
                      default: 1h
                    freeSpacePercentage:
                      $ref: '#/$defs/pct'
                      default: 30
                    hours:
                      default: 24
                      type: number
                    pattern:
                      additionalProperties: false
                      properties:
                        exclude:
                          additionalProperties: false
                          properties:
                            disk:
                              default: ""
                              type: string
                            node:
                              default: ""
                              type: string
                          type: object
                        include:
                          additionalProperties: false
                          properties:
                            disk:
                              default: .*
                              type: string
                            node:
                              default: .*
                              type: string
                          type: object
                      type: object
                    severity:
                      default: warning
                      type: string
                  type: object
                type: array
              space:
                items:
                  additionalProperties: false
                  properties:
                    for:
                      default: 30m
                      type: string
                    freeSpacePercentage:
                      $ref: '#/$defs/pct'
                      default: 5
                    pattern:
                      additionalProperties: false
                      properties:
                        exclude:
                          additionalProperties: false
                          properties:
                            disk:
                              default: ""
                              type: string
                            node:
                              default: ""
                              type: string
                          type: object
                        include:
                          additionalProperties: false
                          properties:
                            disk:
                              default: .*
                              type: string
                            node:
                              default: .*
                              type: string
                          type: object
                      type: object
                    severity:
                      default: warning
                      type: string
                  type: object
                type: array
            type: object
        type: object
      nodeSelector:
        $ref: '#/$defs/nodeSelector'
      replicas:
        default: 1
        type: number
      resources:
        $ref: '#/$defs/resources'
      retention:
        additionalProperties: false
        properties:
          age:
            default: 3d
            type: string
          alertmanager:
            $ref: '#/$defs/timeRange'
            default: 72h
          size:
            default: 4GiB
            type: string
        type: object
      s3BucketAlerts:
        additionalProperties: false
        properties:
          exclude:
            type: array
          objects:
            additionalProperties: false
            properties:
              count:
                default: 1638400
                type: number
              enabled:
                default: false
                type: boolean
              percent:
                $ref: '#/$defs/pct'
                default: 80
            type: object
          size:
            additionalProperties: false
            properties:
              enabled:
                default: false
                type: boolean
              percent:
                $ref: '#/$defs/pct'
                default: 80
              sizeQuotaGB:
                default: 1000
                type: number
            type: object
        type: object
      storage:
        additionalProperties: false
        properties:
          enabled:
            default: false
            type: boolean
          size:
            default: 5Gi
            type: string
        type: object
      tolerations:
        $ref: '#/$defs/tolerations'
      topologySpreadConstraints:
        $ref: '#/$defs/topologySpreadConstraints'
    type: object
  prometheusBlackboxExporter:
    additionalProperties: false
    properties:
      customKubeapiTargets:
        items:
          properties:
            domain:
              format: hostname
              type: string
            name:
              type: string
          type: object
        type: array
      hostAliases:
        items:
          properties:
            hostNames:
              items:
                type: string
              type: array
            ip:
              format: ipv4
              type: string
          type: object
        type: array
      resources:
        $ref: '#/$defs/resources'
      targets:
        properties:
          additionalProperties:
            type: boolean
        type: object
    type: object
additionalProperties:
  type: object
  properties: {}
