harbor:
  persistence:
    type: objectStorage
    disableRedirect: false

fluentd:
  logManager:
    compaction:
      # azcopy is used by az CLI for downloading files
      azureCopyBufferGB: 0.3
      azureCopyConcurrency: 8

objectStorage:
  sync:
    ## If Harbor or Thanos are using swift then we will automatically use swift for the sync, regardless of the value set for type.
    destinationType: azure
