{
 "title": "Thanos / Receive",
 "tags": [ "thanos-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "tenant",
    "label": "tenant",
    "query": "label_values(http_requests_total{job=~\"$job\", tenant!=\"\"}, tenant)"
   },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{job=~\".*thanos-receiver-receive.*\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "WRITE - Incoming Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, handler, code) (rate(http_requests_total{job=~\"$job\", handler=\"receive\"}[$interval]))",
     "legendFormat": "{{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{job=~\"$job\", handler=\"receive\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (job) (rate(http_requests_total{job=~\"$job\", handler=\"receive\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle incoming requests in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "WRITE - Incoming Request (tenant focus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of write requests (by tenant and code)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant, code) (rate(http_requests_total{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\"}[$__rate_interval]))",
     "legendFormat": "{{code}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Number of errors (by tenant and code)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant, code) (rate(http_requests_total{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{code}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Average request duration (by tenant)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, tenant) (rate(http_request_duration_seconds_sum{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\"}[$__rate_interval])) / sum by (job, tenant) (http_request_duration_seconds_count{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "HTTP requests (tenant focus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average successful HTTP request size (per tenant and code, only 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, tenant) (rate(http_request_size_bytes_sum{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code=~\"2..\"}[$__rate_interval])) / sum by (job, tenant) (rate(http_request_size_bytes_count{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Average failed HTTP request size (per tenant and code, non 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, tenant) (rate(http_request_size_bytes_sum{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code!~\"2..\"}[$__rate_interval])) / sum by (job, tenant) (rate(http_request_size_bytes_count{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Inflight requests (per tenant and method)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, tenant, method) (http_inflight_requests{job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\"})",
     "legendFormat": "{{method}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Series & Samples (tenant focus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of series received (per tenant, only 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_receive_write_timeseries_sum{job=~\"$job\", tenant=~\"$tenant\", code=~\"2..\"}[$__rate_interval])) by (job, tenant) ",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of series not written (per tenant and code, non 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_receive_write_timeseries_sum{job=~\"$job\", tenant=~\"$tenant\", code!~\"2..\"}[$__rate_interval])) by (tenant, code) ",
     "legendFormat": "{{code}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of samples received (per tenant, only 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_receive_write_samples_sum{job=~\"$job\", tenant=~\"$tenant\", code=~\"2..\"}[$__rate_interval])) by (job, tenant) ",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of samples not written (per tenant and code, non 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_receive_write_samples_sum{job=~\"$job\", tenant=~\"$tenant\", code!~\"2..\"}[$__rate_interval])) by (tenant, code) ",
     "legendFormat": "{{code}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "WRITE - Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of replications to other receive nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_receive_replications_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "all {{job}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of replications to other receive nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_receive_replications_total{job=~\"$job\", result=\"error\"}[$interval])) / sum by (job) (rate(thanos_receive_replications_total{job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "WRITE - Forward Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of forwarded requests to other receive nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_receive_forward_requests_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "all {{job}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of forwarded requests to other receive nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_receive_forward_requests_total{job=~\"$job\", result=\"error\"}[$interval])) / sum by (job) (rate(thanos_receive_forward_requests_total{job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "WRITE - gRPC (Unary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))",
     "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "READ - gRPC (Unary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))",
     "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "READ - gRPC (Stream)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Streamed gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"$job\", grpc_type=\"server_stream\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Last Updated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Successful Upload",
   "type": "table",
   "description": "Shows the relative time of last successful upload to the object-store bucket.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time() - max by (job, bucket) (thanos_objstore_bucket_last_successful_upload_time{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$job\"}",
     "legendFormat": "alloc all {{instance}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\"}",
     "legendFormat": "alloc heap {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\"}[30s])",
     "legendFormat": "alloc rate all {{instance}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$job\"}[30s])",
     "legendFormat": "alloc rate heap {{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\"}",
     "legendFormat": "inuse heap {{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\"}",
     "legendFormat": "inuse stack {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\"}",
     "legendFormat": "{{quantile}} {{instance}}"
    }
   ]
  }
 ]
}