#!/usr/bin/env bats

# These tests are generated into these files:
# - tests/unit/validate/test-kubespray-aws-air-gapped.gen.bats
# - tests/unit/validate/test-kubespray-aws-dev.gen.bats
# - tests/unit/validate/test-kubespray-aws-prod.gen.bats
# - tests/unit/validate/test-kubespray-baremetal-air-gapped.gen.bats
# - tests/unit/validate/test-kubespray-baremetal-dev.gen.bats
# - tests/unit/validate/test-kubespray-baremetal-prod.gen.bats
# - tests/unit/validate/test-kubespray-citycloud-air-gapped.gen.bats
# - tests/unit/validate/test-kubespray-citycloud-dev.gen.bats
# - tests/unit/validate/test-kubespray-citycloud-prod.gen.bats
# - tests/unit/validate/test-kubespray-elastx-air-gapped.gen.bats
# - tests/unit/validate/test-kubespray-elastx-dev.gen.bats
# - tests/unit/validate/test-kubespray-elastx-prod.gen.bats
# - tests/unit/validate/test-kubespray-exoscale-air-gapped.gen.bats
# - tests/unit/validate/test-kubespray-exoscale-dev.gen.bats
# - tests/unit/validate/test-kubespray-exoscale-prod.gen.bats
# - tests/unit/validate/test-kubespray-safespring-air-gapped.gen.bats
# - tests/unit/validate/test-kubespray-safespring-dev.gen.bats
# - tests/unit/validate/test-kubespray-safespring-prod.gen.bats
# - tests/unit/validate/test-kubespray-upcloud-air-gapped.gen.bats
# - tests/unit/validate/test-kubespray-upcloud-dev.gen.bats
# - tests/unit/validate/test-kubespray-upcloud-prod.gen.bats
# - tests/unit/validate/test-kubespray-openstack-air-gapped.gen.bats
# - tests/unit/validate/test-kubespray-openstack-dev.gen.bats
# - tests/unit/validate/test-kubespray-openstack-prod.gen.bats
# - tests/unit/validate/test-capi-aws-air-gapped.gen.bats
# - tests/unit/validate/test-capi-aws-dev.gen.bats
# - tests/unit/validate/test-capi-aws-prod.gen.bats
# - tests/unit/validate/test-capi-baremetal-air-gapped.gen.bats
# - tests/unit/validate/test-capi-baremetal-dev.gen.bats
# - tests/unit/validate/test-capi-baremetal-prod.gen.bats
# - tests/unit/validate/test-capi-citycloud-air-gapped.gen.bats
# - tests/unit/validate/test-capi-citycloud-dev.gen.bats
# - tests/unit/validate/test-capi-citycloud-prod.gen.bats
# - tests/unit/validate/test-capi-elastx-air-gapped.gen.bats
# - tests/unit/validate/test-capi-elastx-dev.gen.bats
# - tests/unit/validate/test-capi-elastx-prod.gen.bats
# - tests/unit/validate/test-capi-exoscale-air-gapped.gen.bats
# - tests/unit/validate/test-capi-exoscale-dev.gen.bats
# - tests/unit/validate/test-capi-exoscale-prod.gen.bats
# - tests/unit/validate/test-capi-safespring-air-gapped.gen.bats
# - tests/unit/validate/test-capi-safespring-dev.gen.bats
# - tests/unit/validate/test-capi-safespring-prod.gen.bats
# - tests/unit/validate/test-capi-upcloud-air-gapped.gen.bats
# - tests/unit/validate/test-capi-upcloud-dev.gen.bats
# - tests/unit/validate/test-capi-upcloud-prod.gen.bats
# - tests/unit/validate/test-capi-openstack-air-gapped.gen.bats
# - tests/unit/validate/test-capi-openstack-dev.gen.bats
# - tests/unit/validate/test-capi-openstack-prod.gen.bats
