#!/usr/bin/env bats

# These tests are generated into these files:
# - tests/unit/validate/test-aws-capi-air-gapped.gen.bats
# - tests/unit/validate/test-aws-capi-dev.gen.bats
# - tests/unit/validate/test-aws-capi-prod.gen.bats
# - tests/unit/validate/test-aws-kubespray-air-gapped.gen.bats
# - tests/unit/validate/test-aws-kubespray-dev.gen.bats
# - tests/unit/validate/test-aws-kubespray-prod.gen.bats
# - tests/unit/validate/test-baremetal-capi-air-gapped.gen.bats
# - tests/unit/validate/test-baremetal-capi-dev.gen.bats
# - tests/unit/validate/test-baremetal-capi-prod.gen.bats
# - tests/unit/validate/test-baremetal-kubespray-air-gapped.gen.bats
# - tests/unit/validate/test-baremetal-kubespray-dev.gen.bats
# - tests/unit/validate/test-baremetal-kubespray-prod.gen.bats
# - tests/unit/validate/test-citycloud-capi-air-gapped.gen.bats
# - tests/unit/validate/test-citycloud-capi-dev.gen.bats
# - tests/unit/validate/test-citycloud-capi-prod.gen.bats
# - tests/unit/validate/test-citycloud-kubespray-air-gapped.gen.bats
# - tests/unit/validate/test-citycloud-kubespray-dev.gen.bats
# - tests/unit/validate/test-citycloud-kubespray-prod.gen.bats
# - tests/unit/validate/test-elastx-capi-air-gapped.gen.bats
# - tests/unit/validate/test-elastx-capi-dev.gen.bats
# - tests/unit/validate/test-elastx-capi-prod.gen.bats
# - tests/unit/validate/test-elastx-kubespray-air-gapped.gen.bats
# - tests/unit/validate/test-elastx-kubespray-dev.gen.bats
# - tests/unit/validate/test-elastx-kubespray-prod.gen.bats
# - tests/unit/validate/test-exoscale-capi-air-gapped.gen.bats
# - tests/unit/validate/test-exoscale-capi-dev.gen.bats
# - tests/unit/validate/test-exoscale-capi-prod.gen.bats
# - tests/unit/validate/test-exoscale-kubespray-air-gapped.gen.bats
# - tests/unit/validate/test-exoscale-kubespray-dev.gen.bats
# - tests/unit/validate/test-exoscale-kubespray-prod.gen.bats
# - tests/unit/validate/test-openstack-capi-air-gapped.gen.bats
# - tests/unit/validate/test-openstack-capi-dev.gen.bats
# - tests/unit/validate/test-openstack-capi-prod.gen.bats
# - tests/unit/validate/test-openstack-kubespray-air-gapped.gen.bats
# - tests/unit/validate/test-openstack-kubespray-dev.gen.bats
# - tests/unit/validate/test-openstack-kubespray-prod.gen.bats
# - tests/unit/validate/test-safespring-capi-air-gapped.gen.bats
# - tests/unit/validate/test-safespring-capi-dev.gen.bats
# - tests/unit/validate/test-safespring-capi-prod.gen.bats
# - tests/unit/validate/test-safespring-kubespray-air-gapped.gen.bats
# - tests/unit/validate/test-safespring-kubespray-dev.gen.bats
# - tests/unit/validate/test-safespring-kubespray-prod.gen.bats
# - tests/unit/validate/test-upcloud-capi-air-gapped.gen.bats
# - tests/unit/validate/test-upcloud-capi-dev.gen.bats
# - tests/unit/validate/test-upcloud-capi-prod.gen.bats
# - tests/unit/validate/test-upcloud-kubespray-air-gapped.gen.bats
# - tests/unit/validate/test-upcloud-kubespray-dev.gen.bats
# - tests/unit/validate/test-upcloud-kubespray-prod.gen.bats
