clusterDNS: ""

resources: {}

service:
  ipFamilyPolicy: ""
  ipFamilies:

metricsService:
  ipFamilyPolicy: ""
  ipFamilies: []

hostZone:
  extraConfig: ""

customConfig: ""

image:
  repository: ""
  tag: ""
