name: tests

on:
  pull_request:
    branches:
      - main
      - release-*

jobs:
  unit-static:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - general
          - baremetal
          - citycloud
          - elastx
          - exoscale
          - safespring
          - upcloud
    steps:
      - name: checkout compliantkubernetes-apps
        uses: actions/checkout@v4
      - name: setup docker with buildx
        uses: docker/setup-buildx-action@v3
      - name: build tests container image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          context: .
          target: unit
          file: ./tests/Dockerfile
          load: true
          pull: false
          push: false
          tags: compliantkubernetes-apps-tests:unit
      - name: run static unit tests
        working-directory: ./tests
        env:
          CK8S_AUTO_APPROVE: true
        run: make ctr-run-unit-static,${{ matrix.tag }}

  integration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout compliantkubernetes-apps
        uses: actions/checkout@v4
      - name: setup docker with buildx
        uses: docker/setup-buildx-action@v3
      - name: build tests container image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          context: .
          target: main
          file: ./tests/Dockerfile
          load: true
          pull: false
          push: false
          tags: compliantkubernetes-apps-tests:main
      - name: create local cache
        run: ./scripts/local-cluster.sh cache create
      - name: run integration tests
        working-directory: ./tests
        env:
          CK8S_AUTO_APPROVE: true
        run: make ctr-run-integration
      - name: delete local cache
        if: always()
        run: ./scripts/local-cluster.sh cache delete
